### ISSUE TITLE
IDE-readable API documentation

### ISSUE THREAD

**Issue by ploeh** [hedgehogqa/fsharp-hedgehog#117]
Is there a special reason that the API documentation is written as it is?

In the Visual Studio IDE, the documentation is hard to read:

![image](https://user-images.githubusercontent.com/242165/30661918-ac78340c-9e45-11e7-9b28-d0ad228826d8.png)

Perhaps the formatting is written like that because it's readable in some other editor..?

**Comment by moodmosaic** [comment]
I must admit, this looks horrible in Visual Studio 2015, and perhaps also in Visual Studio 2017 😮 This is a mistake on my part; I should have checked how they render there.

When I was porting the [doctest](http://hackage.haskell.org/package/doctest) part of [examples in source code comments](https://github.com/hedgehogqa/haskell-hedgehog/blob/891b67c85d637441e76a0151ac02f1eb63006a05/hedgehog/src/Hedgehog/Internal/Range.hs#L134-L146) from Haskell, such a tool wasn't available in F#, so [I first wrote my own‒quick and dirty‒version of doctest in F#](https://github.com/moodmosaic/doctest).

At this time, I was using F# mostly from Visual Studio Code and Atom, and I don't remember having *doctests* rendered in such a horrible way...

**Comment by moodmosaic** [comment]
It's not perfect in Visual Studio Code either, but not as horrible as it renders in Visual Studio...

![image](https://user-images.githubusercontent.com/287532/30683706-2d89e056-9eb7-11e7-8b64-a1a32956c2fb.png)

For now, this should definitely be fixed from the F# Hedgehog's side.

**Comment by ploeh** [comment]
Does it make sense to use a Haskell documentation system for F#?

FWIW, the API documentation for FsCheck normally looks fine in Visual Studio. Would you be interested in one or more pull requests that modifies the Hedgehog F# code comments to that format?

**Comment by moodmosaic** [comment]
These examples, in Hedgehog's documentation, are being actually [executed as part of the build process](https://github.com/hedgehogqa/fsharp-hedgehog/blob/67e3921ec5ea632e6fd02216cba0388c7ff1c138/build.fsx#L22-L34). If you can do similar to the API documentation used by FsCheck then that'll be great. 👍

One or more PRs that modifies the Hedgehog F# code comments to that format will be appreciated.

**Comment by ploeh** [comment]
The 'normal' way to do this with F#, I believe, is to use [F# Formatting](http://fsprojects.github.io/FSharp.Formatting).

**Comment by moodmosaic** [comment]
FTR, I find the [FParsec's documentation](http://www.quanttec.com/fparsec/) as a nice F# equivalent to Haskell's [Haddock](https://www.haskell.org/haddock/#Examples). I prefer it over the verbose, IMO, syntax of F# Formatting's literate programming.

However, according to @stephan-tolksdorf, FParsec's documentation is not open-source, and I don't expect anyone to write a doctest add-in for F# IDEs and code editors anytime soon...

Perhaps, [F# Formatting's literate programming](http://fsprojects.github.io/FSharp.Formatting/literate.html) is the way to go. Is that what FsCheck does?

**Comment by ploeh** [comment]
Yes, AFAICT, that's what FsCheck uses.

**Comment by moodmosaic** [comment]
With version 0.4.1 or later, we switched off `doctests` and so the XML documentation renders nicely. Closing this while keeping F# Formatting (#118) in mind.
