### ISSUE TITLE
Switch to F# Formatting

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#118]
as a better alternative to our custom doctest implementation.

**Benefits**

1. It removes the noise from the tooltips in the API docs on all major F# IDE's and code editors.
2. It has the ability to execute code examples as part of the build process.
3. It makes it easier to have some sort of HTML documentation.

Right now, with our custom doctest implementation, we're tackling only the 2nd item.

---

See also https://github.com/hedgehogqa/fsharp-hedgehog/issues/117.

**Comment by kurtschelfthout** [comment]
Note https://github.com/fscheck/FsCheck/issues/384

**Comment by jwChung** [comment]
Should we use FAKE to solve this issue?

**Comment by moodmosaic** [comment]
Perhaps, FAKE [can make this easier](http://fsprojects.github.io/ProjectScaffold/writing-docs.html#API-docs) but I don't think it's *required*(?) IIRC, @Porges removed it in #153 since all we needed was doable with the `dotnet` command―no need to maintain pesky `build.fsx` files.

FTR, there's another tool, DocFx which is created by Microsoft, it's open source, and I think it's the one being used in https://docs.microsoft.com/.

Sample: [F# Formatting](https://fake.build/apidocs/v5/index.html#Fake.Api)
Sample: [DocFx](https://dotnet.github.io/docfx/api/Microsoft.DocAsCode.ContentPairingInfo.html)

**Comment by jwChung** [comment]
@moodmosaic  I see. Thank you for your explanation.

**Comment by jwChung** [comment]
[As DocFx says as below, ](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html) it is unlikely to be a solution.

> DocFX is an API documentation generator for .NET, which currently supports C# and VB.

1. If we use [the FSharp.MetadataFormat library](https://fsprojects.github.io/FSharp.Formatting/metadata.html) for API documentation, does it have the ability to execute code examples(Can it check compile errors)?

2. Not using FAKE, which executable program do we use to execute the `FSharp.MetadataFormat.dll` library?

**Comment by moodmosaic** [comment]
>1.
Yes, it looks like [F# support for DocFx](https://github.com/dotnet/docfx/issues/159) isn't there yet. Good catch. So, the [library documentation tool](https://fsprojects.github.io/FSharp.Formatting/metadata.html) of F# Formatting seems like the only choice right now.

>2.
I'd start by just using plain F# Interactive (*fsi*, *fsharpc*) to run a script (say, *doc.fsx*) that generates HTML documentation from the existing XML comments found in Gen.fs, Range.fs, etc.

If this turns out to be working well, then we'll consider what would be an easy way to integrate it as part of the build process.

**Comment by jwChung** [comment]
It seems that [the library documentation tool](https://fsprojects.github.io/FSharp.Formatting/metadata.html) doesn't have ability to execute code examples in XML comments.

**Comment by moodmosaic** [comment]
I guess it's done by the [literate programming](https://fsprojects.github.io/FSharp.Formatting/literate.html) tool, part of that same suite(?)
