### ISSUE TITLE
Add default generators for brevity

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#123]
I've just barely started experimenting with Hedgehog. I've previously used FsCheck, and what I really like about FsCheck is its simplicity. For many tests with simple (mostly primitive) inputs, I can simply define the test as a function of the relevant parameters and off we go.

Hedgehog on the other hand seems to require me to explicitly state in all tests how values are generated, even for simple primitive types like ints. For example, here's a test for a function `constrain` that constrains an int to a given interval (I'm using Xunit and Unquote):

```f#
[<Fact>]
let ``interval order doesn't matter`` () = Property.check <| property {
  let! x1, x2, x = Range.exponentialBounded() |> Gen.int |> Gen.tuple3
  test <@ constrain (x1, x2) x = constrain (x2, x1) x @> }
```

Here's the same in FsCheck:

```f#
[<Property>]
let ``interval order doesn't matter`` (x1:int) x2 x =
  test <@ constrain (x1, x2) x = constrain (x2, x1) x @>
```

Now, I've read blog posts and FsCheck issue discussions with strong arguments from @ploeh for why it's safer to explicitly define how values are generated, and I certainly get that for more complex or constrained types. Still, having to explicitly create default generators (e.g. specifying ranges for ints, ranges and character generators for strings) for even the most simple types seems a bit long-winded when all I want much of the time is to say "gimme a string" or "gimme an int".

This is of course not helped by there being almost no documentation (I've only found the tutorial, and there seems to be very little doc comments), forcing me to experiment myself to e.g. realize that `exponentialBounded` seems a good choice for a default int generator (and likely several other generators). And while I can just factor that out to common test generators, that would need to be repeated for all test projects. All things considered, Hedgehog as compared to FsCheck might be a bit of a hard sell to my colleagues (I'm doing an F# course for my company this week and wondering if I should recommend FsCheck or Hedgehog).

What do you think about defining some standard generators for primitive types (ints, strings, etc.) to make some of the Hedgehog usage simpler?

I'm completely open to this being a terrible idea for whatever reason. If that is the case, please let me know why so that I can learn.

**Comment by moodmosaic** [comment]
The problem with the 'default' generators is that it's not always clear what the *optimum* 'default' should be.

For example, on [this](https://youtu.be/AIv_9T0xKEo?t=710) video at 11:50 (up to 13:09), @jystic shows how a bug slipped in [bos/text](https://github.com/bos/text) library by using QuickCheck's default arbitraries.

Currently, there's one combinator per type, as in the Haskell version of Hedgehog, and so it should be easy to experiment with writing 'default' generators by combining the primitives that we currently offer.

**Comment by moodmosaic** [comment]
We are working on the documentation (https://github.com/hedgehogqa/fsharp-hedgehog/issues/118) as we're still in version < 1. In the meantime, you may find [these examples on `Range` type and combinators](https://github.com/hedgehogqa/fsharp-hedgehog/blob/master/tests/Hedgehog.Tests/RangeTests.fs) useful, as well as [this](https://github.com/hedgehogqa/haskell-hedgehog/issues/120) discussion on the Haskell version.

**Comment by moodmosaic** [comment]
On simplicity, Hedgehog combines a minimal API, [a `property` expression that makes tests less fragmented](http://blog.nikosbaxevanis.com/2017/04/10/less-fragmented-properties-with-hedgehog/), and [integrated shrinking](http://hypothesis.works/articles/integrated-shrinking/):

```f#
/// A generator for random instants in time, expressed as
/// a date and time of day that shrinks towards year 2000.
let dateTime : Gen<DateTime> =
    let yMin = DateTime.MinValue.Year
    let yMax = DateTime.MaxValue.Year
    gen {
        let! y = Gen.integral <| Range.linearFrom 2015 yMin yMax
        let! m = Gen.integral <| Range.constant 1 12
        let! d = Gen.integral <| Range.constant 1 (DateTime.DaysInMonth (y, m))
        let! h = Gen.integral <| Range.constant 0 23
        let! n = Gen.integral <| Range.constant 0 59
        let! s = Gen.integral <| Range.constant 0 59

        return DateTime (y, m, d, h, n, s)
    }
``` 

That's a `Gen<DateTime>` generator with integrated shrinking towards the year 2015. Here's [a similar for FsCheck](https://github.com/fscheck/FsCheck/blob/3a0fe2ab780019aec9683b855fda0c3b99db45fd/src/FsCheck/Arbitrary.fs#L717-L736), and [perhaps one for QuickCheck can be found here](https://github.com/phadej/qc-instances/blob/master/src/Test/QuickCheck/Instances.hs).

**Comment by moodmosaic** [comment]
In case it helps, here's also [a sample PR that converts an FsCheck-based test-suite into Hedgehog](https://github.com/ploeh/PollingConsumer/pull/2/files).

**Comment by cmeeren** [comment]
Thanks for the explanations and links! Feel free to close this.

By the way, do you know how far off v1 is, or at least more substantial documentation?

**Comment by moodmosaic** [comment]
>do you know how far off v1 is

Once @Porges has finalized https://github.com/hedgehogqa/fsharp-hedgehog/pull/113, and we add support for abstract state-machine testing in https://github.com/hedgehogqa/fsharp-hedgehog/issues/110, it should be fair to have Hedgehog 1.0 out.

>or at least more substantial documentation

I believe there will be a huge difference once we add F# Formatting in #118.

**Comment by moodmosaic** [comment]
Also, on the documentation, you might find [the Hedgehog exploration script](https://github.com/hedgehogqa/fsharp-hedgehog/blob/master/src/Hedgehog/Script.fsx) inside the `Src` folder useful.
