### ISSUE TITLE
Size does not increase if `where` clause is not passed?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#124]
Consider the following test:

```f#
[<Fact>]
let ``constrain returns lower interval value if input is below interval`` () = Property.check <| property {
  let! x1, x2, x = Range.exponentialBounded() |> Gen.int |> Gen.tuple3
  let lower = min x1 x2
  where (x < lower)
  test <@ constrain (x1, x2) x = lower @> }
```

This fails after 100 discards. When I debug, I see that the only value that is generated, even after many tests, is `0`. When I remove the `where` clause, I see other values from the second test run (which probably fails due to the missing conditional).

Is this a bug, or have I not understood how to use Hedgehog?

**Comment by cmeeren** [comment]
Here's a minimal example:

```f#
Property.check <| property {
  let! s = Range.exponentialBounded() |> Gen.int
  where (s <> 0)
  true
}
```

Output:

```
Hedgehog.GaveUpException
*** Gave up after 100 discards, passed 0 tests.
   at Hedgehog.ReportModule.tryRaise(Report report)
   at ...
```

If you remove the `where` line, it passes.

**Comment by moodmosaic** [comment]
This looks like a bug. I haven't given it much thought yet but I think it's because we're not increasing the size [in the `Discard` case](https://github.com/hedgehogqa/fsharp-hedgehog/blob/763cd0000047ede067669816e6e783d783e1931e/src/Hedgehog/Property.fs#L332). Something like this ought to work:

```diff
diff --git a/src/Hedgehog/Property.fs b/src/Hedgehog/Property.fs
index 856eaee..ae695d7 100644
--- a/src/Hedgehog/Property.fs
+++ b/src/Hedgehog/Property.fs
@@ -329,7 +329,7 @@ module Property =
                 | Success () ->
                     loop seed2 (nextSize size) (tests + 1<tests>) discards
                 | Discard ->
-                    loop seed2 size tests (discards + 1<discards>)
+                    loop seed2 (nextSize size) tests (discards + 1<discards>)

         let seed = Seed.random ()
         loop seed 1 0<tests> 0<discards>
```

/cc @jystic

**Comment by cmeeren** [comment]
That seems like a reasonable explanation and fix.

**Comment by moodmosaic** [comment]
Fixed in 1f578dc and released as Hedgehog 0.4.2.

**Comment by moodmosaic** [comment]
@cmeeren, is your twitter handle [@cmeeren](https://mobile.twitter.com/cmeeren)? If so, may I mention you on the Tweet for the new release? 😃

**Comment by cmeeren** [comment]
Yep! 👍
