### ISSUE TITLE
Suggestion: Remove <tests> unit from check'

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#131]
I suggest to remove the `<tests>` unit of measure from `Property.check'`. I don't see the point - it adds no clarity, and I can't see how the added type safety gives any benefit in this particular case. I think it just adds noise.

Just a suggestion. :)

**Comment by moodmosaic** [comment]
```f#
Property.check' 999
```
vs

```f#
Property.check' 999<tests>
```

Hmm... that's interesting.

**Comment by moodmosaic** [comment]
Either way would be fine for me, so what do you think @jystic?

**Comment by jystic** [comment]
I prefer having it, perhaps it's just my haskell background coming out where I tend not to have raw integers / strings anywhere at all, I always `newtype` them. The reason for having it was more about type safety internally than in the external API, so I could be convinced to remove it from the public API and keep using it internally.

**Comment by moodmosaic** [comment]
Hmm... Perhaps, *explicit* is better than implicit, as per [The Zen of Python](https://www.python.org/dev/peps/pep-0020/).

```f#
Property.check' 999<tests> <| property { return true }
```

vs

```f#
roperty.check' 999 <| property { return true } 
```

I would say, let's close this for now.

We may always go back and reopen it, and we can keep the discussion going even if it's closed.

**Comment by cmeeren** [comment]
> Hmm... Perhaps, explicit is better than implicit, as per The Zen of Python.

While I fully support this in some areas (I even come from a Python background), it kind of goes against some core features of F#, such as type inference. Just sayin' 😉 

I'm content with having to write `999<tests>` though; there are bigger fish to fry here (#135 being the biggest IMHO).

**Comment by jystic** [comment]
> it kind of goes against some core features of F#, such as type inference

Interestingly, in the Haskell version, the `TestCount` type has a `Num` instance, which means you can just write `999` and it constructs a `TestCount`. So it's convenient, but you also get the type safety from that point onwards.
