### ISSUE TITLE
How to use Gen.float?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#132]
I'm trying to generate floats, but if I write `Gen.float (Range.exponentialBounded())` I just get an error saying `No overloads match for method 'ToBigInt'.`

I have searched this repo for "float" but no usages seemed to turn up. How can I generate floats?

**Comment by moodmosaic** [comment]
Thank you for reporting this. We use [parts from FsControl](https://github.com/hedgehogqa/fsharp-hedgehog/blob/master/src/Hedgehog/Numeric.fs) and I'm guessing that this issue might be related somehow. It's the same also with `Gen.double` 😮

**Comment by moodmosaic** [comment]
Fixed in ebfbaa3 and released as Hedgehog 0.4.3.
