### ISSUE TITLE
Gen.filter vs. 'where' clause

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#134]
Often I have the choice whether to use `Gen.filter` to only generate valid values in a given test, or use `where` after generation to skip the test for invalid values.

Is either of these preferred? Is there, for example, a performance difference? Or any other reasons why one should be preferred over the other?

**Comment by moodmosaic** [comment]
`where` is `Property.filter` and the difference is that the filtering happens *after* you have generated a value:

```f#
Property.print <| property {
    let! n = Gen.int <| Range.constantBounded ()
    where (n = 987654321)
    return 1 / n = 1 / n
}

*** Gave up after 100 discards, passed 0 tests.
val it : unit = ()
> 
```

`Gen.filter` may be preferred if there's a high chance that the predicate is satisfied, or else it'll run forever:

```f#
Property.print <| property {
    let! n = Gen.filter (fun n -> n = 987654321) (Gen.int <| Range.constantBounded ())
    return 1 / n = 1 / n
}

// (Can take a while to finish, until 987654321 gets generated(!))
```

**Comment by cmeeren** [comment]
AFAIK, a low chance of predicate returning true leads to a failure state anyway (test runs forever or test fails). According to my understanding, this means that such predicates must be avoided at all costs anyway. Is that correct, and does that mean that there's really no significant reason to choose one over the other with regards to `where`/`Gen.filter`?

**Comment by moodmosaic** [comment]
>[..] this means that such predicates must be avoided at all costs

Yes

>[..] that there's really no significant reason to choose one over the other

Yes—actually, if you know there's low chance to satisfy the predicate, perhaps you can try `Gen.tryFilter`.

**Comment by jystic** [comment]
>  Is that correct, and does that mean that there's really no significant reason to choose one over the other with regards to where/Gen.filter?

I would prefer `Gen.filter` because it means that only that specific generator will be retried, where as with `where` the entire test is thrown away and retried. So `Gen.filter` is fundamentally faster.

**Comment by moodmosaic** [comment]
Closing this, but feel free to add comments to it.
