### ISSUE TITLE
Include batteries

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#139]
One of Hedgehog's main strengths, IMHO, is its flexibility due to all the `Gen` combinators. However, practical use entirely depends on the user to define commonly used combinations themselves to avoid too much tedious repetition in the tests, and then either repeat these definitions for each test project, or create a separate solution/assembly with common usecases and add that to all test projects. I think most people will just copy-paste the same common combinations across all of their test projects (copy-paste).

I'd like Hedgehog to have a bit more "batteries included" approach. This would make the framework a much easier sell, so to speak. This could either be done by including common shortcuts in Hedgehog itself, or it could be released as a separate nuget (Hedgehog.Batteries?) maintained by Hedgehog maintainers or someone else. If it's a separate library maintained by someone else, it should preferably be officially endorsed by Hedgehog.

Here are examples of what I'm talking about (I'm not saying everything here must be included):

```f#
namespace Hedgehog.Batteries

module Gen =

  open Hedgehog

  /// Generates an int using sensible defaults (Range.exponentialBounded)
  let dInt = Gen.int <| Range.exponentialBounded()

  /// Generates a string using sensible defaults (Range.exponential 0 50, latin1)
  let dString = Gen.string (Range.exponential 0 50) Gen.latin1

  /// Generates a list using sensible defaults (Range.exponential 0 50)
  let dList g =
    g |> Gen.list (Range.exponential 0 50)

  /// Generates a list with length determined using Range.exponential lower upper
  let eList lower upper =
    Gen.list (Range.exponential lower upper)

  /// Generates a list with length determined using Range.linear lower upper
  let lList lower upper =
    Gen.list (Range.linear lower upper)

  /// Generates a list with length determined using Range.constant lower upper
  let cList lower upper =
    Gen.list (Range.constant lower upper)

  /// Generates null part of the time
  let withNull g =
    g |> Gen.option |> Gen.map (fun xOpt ->
      match xOpt with Some x -> x | None -> null)

  /// Generates a value that is not null
  let noNull g =
    g |> Gen.filter (not << isNull)

  /// Generates a value that is not equal to another value
  let notEqual other =
    Gen.filter ((<>) other)

  /// Generates a value that is not equal to another option-wrapped value
  let notEqualOpt other =
    Gen.filter (fun x -> match other with Some o -> x <> o | None -> true)


  /// Generates a 2-tuple with sorted elements.
  let sorted2 g =
    g |> Gen.map (fun (x1, x2) -> 
           let l = [x1; x2] |> List.sort
           (l.Item 0, l.Item 1))

  /// Generates a 3-tuple with sorted elements.
  let sorted3 g =
    g |> Gen.map (fun (x1, x2, x3) -> 
           let l = [x1; x2; x3] |> List.sort
           (l.Item 0, l.Item 1, l.Item 2))

  /// Generates a 4-tuple with sorted elements.
  let sorted4 g =
    g |> Gen.map (fun (x1, x2, x3, x4) -> 
           let l = [x1; x2; x3; x4] |> List.sort
           (l.Item 0, l.Item 1, l.Item 2, l.Item 3))

  /// Generates a 2-tuple with distinct elements.
  let distinct2 g =
    g |> Gen.filter (fun (x1, x2) -> x1 <> x2)

  /// Generates a 3-tuple with distinct elements.
  let distinct3 g =
    g |> Gen.filter (fun (x1, x2, x3) -> 
           [x1; x2; x3] |> List.distinct = [x1; x2; x3])

  /// Generates a 4-tuple with distinct elements.
  let distinct4 g =
    g |> Gen.filter (fun (x1, x2, x3, x4) -> 
           [x1; x2; x3; x4] |> List.distinct = [x1; x2; x3; x4])

  /// Generates a 2-tuple with strictly increasing elements
  let increasing2 g =
    g |> sorted2 |> distinct2

  /// Generates a 3-tuple with strictly increasing elements
  let increasing3 g =
    g |> sorted3 |> distinct3

  /// Generates a 4-tuple with strictly increasing elements
  let increasing4 g =
    g |> sorted4 |> distinct4

  /// Generates a tuple of datetimes where the range determines the number
  /// of days apart (positive numbers -> increasing order and vice versa).
  let dateInterval dayRange =
    gen {
      let tickRange = 
        dayRange 
        |> Range.map (fun days -> int64 days * System.TimeSpan.TicksPerDay)
      let! ticksApart = Gen.integral tickRange
      let! dt1 = Gen.dateTime |> Gen.filter (fun dt -> 
        dt.Ticks + ticksApart > System.DateTime.MinValue.Ticks
        && dt.Ticks + ticksApart < System.DateTime.MaxValue.Ticks)
      let dt2 = dt1.AddTicks ticksApart
      return dt1, dt2
    }


  /// Generates a list using inpGen together with a function that maps each of
  /// the distinct elements in the list to values generated by outGen. Distinct
  /// elements in the input list may possibly map to the same values. The generated
  /// function throws if called with values not in the input list.
  let withMapTo (outGen:Gen<'b>) (inpGen:Gen<'a list>) : Gen<'a list * ('a->'b)> =
    gen {
      let! inputs = inpGen
      let! outputs = outGen |> Gen.list (Range.singleton inputs.Length)
      let inOutMap = List.zip inputs outputs |> Map.ofList
      return inputs, (fun x -> inOutMap.Item x)
    }

  /// Generates a list using inpGen together with a function that maps each of
  /// the distinct elements in the list to values generated by outGen. Distinct
  /// elements in the input list are guaranteed to map to distinct values. Only
  /// use this if the output space is large enough that a list of distinct output
  /// values is likely to be generated. The generated function throws if called
  /// with values not in the input list.
  let withDistinctMapTo (outGen:Gen<'b>) (inpGen:Gen<'a list>) : Gen<'a list * ('a->'b)> =
    gen {
      let! inputs = inpGen
      let! outputs =
        outGen
        |> Gen.list (Range.singleton inputs.Length)
        |> Gen.filter (fun lst -> lst = List.distinct lst)
      let inOutMap = List.zip inputs outputs |> Map.ofList
      return inputs, (fun x -> inOutMap.Item x)
    }

  /// Inserts the given element at a random place in the list
  let addElement (x:'a) (g:Gen<'a list>) =
    gen {
      let! xs = g
      let! i = Gen.integral (Range.constant 0 xs.Length)
      let l1, l2 = xs |> List.splitAt i
      return List.concat [l1; [x]; l2]
    }
```

**Comment by cmeeren** [comment]
The `addElement` might seem a bit random to include at first, but I've found it highly useful for tests that are verifying what happens when a (random) list contains a known element.

**Comment by moodmosaic** [comment]
We could definitely take some of those generators that don't use an explicit `Range` internally: `distinct2`,  `sorted2`, etc. These could just be in the existing `Gen` module.

On the other hand, I'm a bit concerned about `dInt`, `dList`, etc., as these generators use an exponential range, and I can imagine pull requests being opened just to change the range to linerar.

I think, a 'batteries included' approach could work by having nested modules in `Gen` something like:

```
Gen module
│   Our existing generators, which most of them take a Range type, e.g.:
│   Int
│   List   
│   ...
│
└───Default (nested module)
│   │
│   └───Lineral (nested module)
│       │   Int
│       │   List
│       │   ...
│   │
│   └───Constant (nested module)
│       │   Int
│       │   List
│       │   ...
│   │
│   └───Exponential
│       │   Int
│       │   List
│       │   ...
```

So, if you need a 'default' generator for integers using linear range, you'd access it like

```f#
let g = Gen.Default.Linear.Int
```

And if you need a 'default' generator for integers using constant (or exponential) range:

```f#
let g = Gen.Default.Constant.Int
```

---

And here's the most interesting part, I think:

What would be the difference between:

```f#
let g = Gen.int <| Range.linearBounded ()
```

and

```f#
let g = Gen.Default.Linear.Int
```

😕 

---

Thoughts? /cc @jystic

**Comment by cmeeren** [comment]
Sidenote: One could open `Gen.Default` and just say `Linear.int` and `Constant.int` in tests. But aside from marginally clearer naming, that seems to provide little benefit against simply having `lInt` and `cInt` in the `Gen` module (or in an auto-opened submodule for internal code organization, but that would be transparent to the user).

**Comment by moodmosaic** [comment]
I'm almost positive about including some (if not all) of those generators. I think `lList`, `eList`, `cList`, etc., are cryptic names, no? Aren't `Linear.list`, `Exponential.list`, `Constant.list`, etc., more descriprive? 😕

**Comment by cmeeren** [comment]
Are names like `Exponential.list` more descriptive than `eList`? Sure. But the prefix `e` is not difficult to learn. Besides, since the documentation for the function is something like `/// Shortcut for list (Range.exponential lower upper)`, it should be self-explanatory. And once one understands the prefixes `e` , `l`, and `c` (likely one of the easier parts of learning to use Hedgehog), using combinators in tests can be notably shorter. Consider:

```f#
Gen.int |> Gen.eList 1 10  // 25 chars
Gen.int |> Gen.Exponential.list 1 10  // 37 chars
Gen.int |> Gen.list (Range.exponential 1 10)  // 46 chars
```

As you see, `Exponential.list` is closer to the full `Gen.list (Range.exponential)` than `Gen.eList`. Since the goal of `eList` and `Gen.Exponential.list` is to allow terser definitions of in-test combinators, I'd say `eList` is much better.

That's just my opinion, though. :)

**Comment by cmeeren** [comment]
An inbetween possibility is to have submodules called `E`, `L`, and `C`, and place `list` etc. inside these. The modules would of course be documented properly, e.g.:

```f#
/// Contains exponentially scaled versions of the basic generators
module E =

  /// Generates a list with length determined using Range.exponential lower upper
  let list lower upper = 
    list <| Range.exponential lower upper
```

Though, aside from marginally better code organization internally in Hedgehog, I can't see how this is much better than just `Gen.eList`.

**Comment by moodmosaic** [comment]
>```f#
>Gen.int |> Gen.eList 1 10  // 25 chars
>Gen.int |> Gen.Exponential.list 1 10  // 37 chars
>Gen.int |> Gen.list (Range.exponential 1 10)  // 46 chars
>```

I'm actually convinced now that `eList` isn't a bad idea. Thank you for your patience!

**Comment by cmeeren** [comment]
Happy to hear it. :) And when/if `auto` is integrated, some defaults are needed anyway, so I think `Gen.dInt`, `Gen.dList` etc. should be included (and that these are directly used from `auto`).

**Comment by moodmosaic** [comment]
I still think it's too much to include the first three generators, `dInt`, `dString`, `dList`, as I think their (short) name doesn't provide any hint at all about what's going on under the cover.

To put it differently:

>```
>Gen.int |> Gen.eList 1 10  // 25 chars
>```

`e` means exponential, and `list` means it is a list, so `eList` isn't *so* hard to learn, perhaps.

However, if `dInt` means just 'default int` then it starts becoming a bit extremely obfuscated(?)

I'd rather suggest we take `dInt`, `dList`, and `dString` inside the `auto` generator—wherever it's going to happen (separate project, NuGet Package, etc), but not expose those 3 directly from the Gen module...

**Comment by cmeeren** [comment]
Sure. :) I'll probably just define some shorthand for `Gen.int <| Range.exponentialBounded()` myself in my own projects then, because I use this all the time in most of my tests (to test generic code). Currently I just have a module called `G` with members like `int` which use sensible defaults, so I just write `G.int` in my tests, which works fine.

**Comment by moodmosaic** [comment]
@jystic, I think it's not a bad idea to include a couple of 'convenience' generators. See an example in https://github.com/hedgehogqa/fsharp-hedgehog/issues/139#issuecomment-338128950. We're talking about including those defined in https://github.com/hedgehogqa/fsharp-hedgehog/issues/139#issue-265767523 except `dInt`, `dList`, `dString`.

**Comment by moodmosaic** [comment]
@cmeeren, do you care opening a PR with all those proposed combinators? (Except those mentioned [here](https://github.com/hedgehogqa/fsharp-hedgehog/issues/139#issuecomment-338133331), which we might consider adding a bit later on.) If you do, it'd be great, otherwise I may try doing it.

In any case, it'd be nice if we also add an example in the [exploration script](https://github.com/hedgehogqa/fsharp-hedgehog/blob/master/src/Hedgehog/Script.fsx) for each one of the combinators.

**Comment by cmeeren** [comment]
Sure, can do. In the `Gen` module, right?

**Comment by cmeeren** [comment]
Also, do you want me to explicitly state all types in function definitions (no type inference)?

**Comment by moodmosaic** [comment]
Yep, it'd be great, now that the codebase is fairly new, if you could follow the existing code-style. In case it helps, it should look something like this:

```f#
//
// Combinators - Convenience
//

/// Generates a list with length determined
/// using Range.exponential lower upper.
let eList (lower : int) (upper : int) : (Gen<'a> -> Gen<List<'a>>) =
    list (Range.exponential lower upper)

/// Generates a list with length determined
/// using Range.linear lower upper.
let lList (lower : int) (upper : int) : (Gen<'a> -> Gen<List<'a>>) =
    list (Range.linear lower upper)

/// Generates a list with length determined
/// using Range.constant lower upper.
let cList (lower : int) (upper : int) : (Gen<'a> -> Gen<List<'a>>) =
    list (Range.constant lower upper)

/// Generates null part of the time.
let withNull (g : Gen<'a>) : Gen<'a> =
    g |> option |> map (fun xOpt ->
    match xOpt with Some x -> x | None -> null)

/// Generates a value that is not null.
let noNull (g : Gen<'a>) : Gen<'a> =
    g |> filter (not << isNull)

/// Generates a value that is not equal to another value.
let notEqual (other :'a) : (Gen<'a> -> Gen<'a>) =
    filter ((<>) other)

/// Generates a value that is not equal to another option-wrapped value.
let notEqualOpt (other :'a option) : (Gen<'a> -> Gen<'a>) =
    filter (fun x -> match other with Some o -> x <> o | None -> true)

/// Generates a 2-tuple with sorted elements.
let sorted2 (g : Gen<'a * 'a>) : Gen<'a * 'a> =
    g |> map (fun (x1, x2) -> 
            let l = [x1; x2] |> List.sort
            (l.Item 0, l.Item 1))

/// Generates a 3-tuple with sorted elements.
let sorted3 (g : Gen<'a * 'a * 'a>) : Gen<'a * 'a * 'a> =
    g |> map (fun (x1, x2, x3) -> 
            let l = [x1; x2; x3] |> List.sort
            (l.Item 0, l.Item 1, l.Item 2))

/// Generates a 4-tuple with sorted elements.
let sorted4 (g : Gen<'a * 'a * 'a * 'a>) : Gen<'a * 'a * 'a * 'a> =
    g |> map (fun (x1, x2, x3, x4) -> 
            let l = [x1; x2; x3; x4] |> List.sort
            (l.Item 0, l.Item 1, l.Item 2, l.Item 3))

/// Generates a 2-tuple with distinct elements.
let distinct2 (g : Gen<'a * 'a>) : Gen<'a * 'a> =
    g |> filter (fun (x1, x2) -> x1 <> x2)

/// Generates a 3-tuple with distinct elements.
let distinct3 (g : Gen<'a * 'a * 'a>) : Gen<'a * 'a * 'a> =
    g |> filter (fun (x1, x2, x3) -> 
            [x1; x2; x3] |> List.distinct = [x1; x2; x3])

/// Generates a 4-tuple with distinct elements.
let distinct4 (g : Gen<'a * 'a * 'a * 'a>) : Gen<'a * 'a * 'a * 'a> =
    g |> filter (fun (x1, x2, x3, x4) -> 
            [x1; x2; x3; x4] |> List.distinct = [x1; x2; x3; x4])

/// Generates a 2-tuple with strictly increasing elements
let increasing2 (g : Gen<'a * 'a>) : Gen<'a * 'a> =
    g |> sorted2 |> distinct2

/// Generates a 3-tuple with strictly increasing elements
let increasing3 (g : Gen<'a * 'a * 'a>) : Gen<'a * 'a * 'a> =
    g |> sorted3 |> distinct3

/// Generates a 4-tuple with strictly increasing elements
let increasing4 (g : Gen<'a * 'a * 'a * 'a>) : Gen<'a * 'a * 'a * 'a> =
    g |> sorted4 |> distinct4

/// Generates a tuple of datetimes where the range determines the number
/// of days apart (positive numbers -> increasing order and vice versa).
let dateInterval (dayRange : Range<int>) : Gen<System.DateTime * System.DateTime> =
    gen {
      let tickRange = 
          dayRange 
          |> Range.map (fun days ->
                  Operators.int64 days * System.TimeSpan.TicksPerDay)
      let! ticksApart = integral tickRange
      let! dt1 = dateTime |> filter (fun dt -> 
          dt.Ticks + ticksApart > System.DateTime.MinValue.Ticks
          && dt.Ticks + ticksApart < System.DateTime.MaxValue.Ticks)
      let dt2 = dt1.AddTicks ticksApart
      return dt1, dt2
    }

/// Generates a list using inpGen together with a function that maps each
/// of the distinct elements in the list to values generated by outGen.
/// Distinct elements in the input list may possibly map to the same values.
/// The generated function throws if called with values not in the input list.
let withMapTo (outGen : Gen<'b>) (inpGen : Gen<'a list>) : Gen<'a list * ('a -> 'b)> =
    gen {
      let! inputs = inpGen
      let! outputs = outGen |> list (Range.singleton inputs.Length)
      let inOutMap = List.zip inputs outputs |> Map.ofList
      return inputs, (fun x -> inOutMap.Item x)
    }

/// Generates a list using inpGen together with a function that maps each
/// of the distinct elements in the list to values generated by outGen.
/// Distinct elements in the input list are guaranteed to map to distinct
/// values. Only use this if the output space is large enough that a list
/// of distinct output values is likely to be generated. The generated
/// function throws if called with values not in the input list.
let withDistinctMapTo (outGen : Gen<'b>) (inpGen : Gen<'a list>) : Gen<'a list * ('a -> 'b)> =
    gen {
      let! inputs = inpGen
      let! outputs =
          outGen
          |> list (Range.singleton inputs.Length)
          |> filter (fun lst -> lst = List.distinct lst)
      let inOutMap = List.zip inputs outputs |> Map.ofList
      return inputs, (fun x -> inOutMap.Item x)
    }

/// Inserts the given element at a random place in the list
let addElement (x : 'a) (g : Gen<'a list>) : Gen<'a list> =
    gen {
      let! xs = g
      let! i = integral (Range.constant 0 xs.Length)
      let l1, l2 = xs |> List.splitAt i
      return List.concat [l1; [x]; l2]
    }
```

**Comment by moodmosaic** [comment]
I think, some functions like `dateInterval`, `sortedN`, `distinctN` could be formatted even further, but that's totally up to you :smiley:

**Comment by moodmosaic** [comment]
Having type annotations, comments ending with `.` and width `< 80` chars we should be good to go. 🚀

**Comment by cmeeren** [comment]
Can do.

Also, which do you prefer of `notEqual` and `notEqualTo`? The latter feels slightly more natural, but is also slightly longer. I don't care that much, though I'm leaning slightly towards `notEqualTo`.

**Comment by moodmosaic** [comment]
`notEqualTo` should be fine and we can always discuss more about the details in the pull request.

**Comment by moodmosaic** [comment]
We had a discussion around this with @jystic, and we ended up leaning towards taking the route of having a separate Hedgehog.*Xyz* where we take combinators from #140, and perhaps the `auto` ones in #133.

This hypothetical GitHub project & NuGet Package may 'deviate' (if that's the right word) from the Haskell version, and it may be hosted under https://github.com/hedgehogqa/. 🚀 🎢 

---

Next we will need to come up with a good name, instead of Hedgehog.*Xyz*. It could be Hedgehog.*Batteries* but that sounds too promising? Perhaps Hedgehog.*X*, [Hedgehog.*Emeralds*](https://en.wikipedia.org/wiki/Sonic_the_Hedgehog#Chaos_Emeralds)? 😅

**Comment by cmeeren** [comment]
A separate nuget sounds good.

IMHO "batteries included" is  fairly well known phrase in software, and means "we've included some non-basic stuff for your convenience". So to me, "Hedgehog.Batteries" sounds clear and not at all "too promising". Another equally clear and less tongue-in-cheek name is "Hedgehog.Convenience". But the name isn't that important to me, so call it whatever you want. :)

**Comment by cmeeren** [comment]
If you can get a project skeleton up and running, I can submit a new PR against that repo.

Should the combinators be in a module "Hedgehog.Convenience.Gen"? (or whatever the project will be called) Or structured differently?

**Comment by moodmosaic** [comment]
Let's wait for @jystic so we can all agree on the name first :cowboy_hat_face:

**Comment by jystic** [comment]
Some other ideas that came to mind:
- `Hedgehog.Contrib`
- `Hedgehog.Experimental` (my intent here is that when combinators are shown to be useful enough we can promote them to the main library)
- `Hedgehog.Extra`
- `Hedgehog.Provisional`

It would be nice if you could access all of the functionality from both using `Gen.xxx`, not sure what's possible in F# around this though?

I would like Hedgehog itself to be batteries included eventually, but I worry about rushing in to making decisions about what the API for that looks like. So I think having something like this for a proving ground is the way to go.

**Comment by moodmosaic** [comment]
>It would be nice if you could access all of the functionality from both using `Gen.xxx`

Yep, they will be defined in a `Gen` module, so once you do `open Hedgehog.Experimental` you should be able to access all of the functionality from both `Gen` modules. 🎉 

I like `Hedgehog.Experimental` by the way. I find it the most descriptive one.

**Comment by cmeeren** [comment]
Sure - if the intent is to potentially promote them to the main library, `Hedgehog.Experimental` seems like the best choice. :)

**Comment by moodmosaic** [comment]
So it looks like we need a new repository called `fsharp-hedgehog-experimental` /cc @jystic

**Comment by jystic** [comment]
Sounds good to me 👍

**Comment by moodmosaic** [comment]
@jystic, are we going to add `fsharp-hedgehog-experimental` to [Hedgehog QA](https://github.com/hedgehogqa/)? If so, can you add it?

The NuGet Package, *Hedgehog (Experimental)* should be under our *[hedgehog](https://www.nuget.org/profiles/hedgehog)* account.

Here's how I imagine this:

![image](https://user-images.githubusercontent.com/287532/32132876-be8f35c6-bbd4-11e7-918b-9d53edf6f959.png)

**Comment by cmeeren** [comment]
When you say "Hedgehog with batteries included", it seems like you intend for the new package to be a standalone package that does not depend on the Hedgehog package. I guess this is not what you meant, so I suggest rephrasing it.

Also, should it be named `Hedgehog (Experimental)` or `Hedgehog.Experimental`?

**Comment by moodmosaic** [comment]
It should take Hedgehog as a dependency... Perhaps it'll be Hedgehog.Experimental as I'm not sure NuGet allows package IDs with spaces(?)

(We can work out on the description before we publish it and discuss about it on the pull request.)

**Comment by moodmosaic** [comment]
@cmeeren, the reason I'd suggest to take Hedgehog as a dependency in Hedgehog.Experimental is because we'll be also taking TypeShape as a dependency too.

Having Hedgehog as a dependency provides feedback—any mistake we made in Hedgehog can quickly show up in Hedgehog.Experimental and vice-versa. There's also going to be less maintenance work.

@jystic, @cmeeren, do you agree on the Hedgehog.Experimental package description [here](https://github.com/hedgehogqa/fsharp-hedgehog/issues/139#issuecomment-340160135)?

**Comment by cmeeren** [comment]
I'd throw in "more combinators" or something like that too.

I completely agree that Hedgehog.Experimental should take Hedgehog as a dependency. I merely meant that the start of the description, "Hedgehog with batteries included", seemed to imply that Hedgehog.Experimental is a standalone package. But it doesn't matter much anyway, because it's clear from the nuget UI that it depends on Hedgehog. In short, I agree with the description (but as said, I suggest mentioning more combinators).

**Comment by jystic** [comment]
@moodmosaic I've created the repository here: https://github.com/hedgehogqa/fsharp-hedgehog-experimental

**Comment by cmeeren** [comment]
Great! Waiting for a project skeleton so I can submit a PR or two.

**Comment by moodmosaic** [comment]
Awesome! Yes, it’ll be ready by tomorrow, hopefully.

**Comment by moodmosaic** [comment]
https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/1 🚀

**Comment by moodmosaic** [comment]
@cmeeren, https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/1 has been merged. I think it's time to move this PR, the `auto` stuff in #133, and the stuff in #125 over there 🎉

**Comment by cmeeren** [comment]
Great! I'll try to do a PR within a day or two.

**Comment by moodmosaic** [comment]
Closing this and opening one with the same title in https://github.com/hedgehogqa/fsharp-hedgehog-experimental/issues/5.
