### ISSUE TITLE
"greedy traversal" test performance

### ISSUE THREAD

**Issue by Porges** [hedgehogqa/fsharp-hedgehog#146]
This is the test in question:

https://github.com/hedgehogqa/fsharp-hedgehog/blob/1dfb754f0a8f3fa1e8806af11054ec21e545fb2e/tests/Hedgehog.Tests/MinimalTests.fs#L65-L89

I ran this under the profiler and the problem is entirely due to the `sprintf` in `forAll`:

https://github.com/hedgehogqa/fsharp-hedgehog/blob/1dfb754f0a8f3fa1e8806af11054ec21e545fb2e/src/Hedgehog/Property.fs#L276-L281

Replacing this with `x.ToString()` reduces the runtime from to 40 s to 0.55 s (!)

However, `ToString` isn't as useful as `sprintf "%A"` for 'native' F# types. A better fix would be to make this function lazily-invoked, so that it's only called if needed.

**Comment by moodmosaic** [comment]
Very interesting. See also #135.

**Comment by Porges** [comment]
@moodmosaic yes, I suspect there's a bunch more easy fixes like this 🙂

**Comment by moodmosaic** [comment]
Fixed in https://github.com/hedgehogqa/fsharp-hedgehog/pull/147 and released as Hedgehog 0.6.

**Comment by cmeeren** [comment]
Just want to let you guys know that this reduced my test suite for a small-ish project (156 tests) from 14 seconds to 4 seconds. Great job, keep it up! 👍
