### ISSUE TITLE
Question: can  fsharp-hedgehog be used in C#?

### ISSUE THREAD

**Issue by jonschoning** [hedgehogqa/fsharp-hedgehog#150]
FSCheck can be used in C# with slightly less convenient ergonomics.

Can fsharp-hedgehog be fully exercised from C# code as well?

**Comment by moodmosaic** [comment]
Thanks for asking! We [support LINQ queries](https://github.com/Porges/fsharp-hedgehog/blob/fbc833c8daaf748d5ff1c36b53f490def0d1ccd3/src/Hedgehog/LinqSupport.fs), if that's what you mean. Some example can be found [here](https://github.com/Porges/fsharp-hedgehog/blob/fbc833c8daaf748d5ff1c36b53f490def0d1ccd3/tests/Hedgehog.CSharp.Tests/LinqTests.cs).

**Comment by jonschoning** [comment]
ah interesting!  Although I'm a bit wary of writing everything using LINQ combinators, it does show that it's at least possible to use fsharp-hedgehog with C#. thanks!

**Comment by moodmosaic** [comment]
>Although I'm a bit wary of writing everything using LINQ combinators

You don't necessarily have to; you can use `Gen.Select`, `Gen.Where`, etcetera, from C# too.
