### ISSUE TITLE
Many functions that take FSharpFunc arguments are very difficult to use from C#

### ISSUE THREAD

**Issue by Porges** [hedgehogqa/fsharp-hedgehog#172]
As in title, this needs to be changed to use `Func` instead.

**Comment by moodmosaic** [comment]
I think there are two options here, either we add a `System.Func<T, TResult>` annotation, or add a façade to expose all the 'incompatible' functions to the rest of .NET in a friendlier way.

**Comment by Porges** [comment]
Also, `Gen.Delay`

**Comment by moodmosaic** [comment]
Or put them on a different module to avoid adding the `Func` suffix? I'm sure I've seen this elsewhere but can't really remember where 😯

**Comment by Porges** [comment]
That would mean you need to use `Gen` in some places and `Gen2` in others?

**Comment by moodmosaic** [comment]
No, that would be messy. Perhaps what you suggest in https://github.com/hedgehogqa/fsharp-hedgehog/issues/172#issuecomment-405812551 is the best we can do.
