### ISSUE TITLE
Print seed to reproduce failure (as FsCheck allows) 

### ISSUE THREAD

**Issue by willsam100** [hedgehogqa/fsharp-hedgehog#179]
In FsChesk, when a test fails, the seed from the random number is printed. The seed can then be feed into the test to reproduce the same failure. 

Can this be done in hedgehog? I could not see examples or any seed output.

**Comment by moodmosaic** [comment]
This isn't supported yet. If we should add support for this, it should be done through the notion of a *runner config*, as [in the Haskell version](https://github.com/hedgehogqa/haskell-hedgehog/blob/14b1262c6eaa3f4b9cf178c338001639f85f8b50/hedgehog/src/Hedgehog/Internal/Runner.hs#L55-L68) (QC and FsCheck are doing similar, IIRC).

(FTR, in the Haskell version specifically, there's a similar discussion about [being able to supply a fixed seed](https://github.com/hedgehogqa/haskell-hedgehog/issues/201#issuecomment-441596807).)

Here in the .NET/F# version, without the notion of a *runner config*, one way of doing what you describe is to modify [`Report`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/70d445497cbba1af550ee45b07e6b85d5145f38d/src/Hedgehog/Property.fs#L26) and [`report'`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/70d445497cbba1af550ee45b07e6b85d5145f38d/src/Hedgehog/Property.fs#L323), though I think having something like a *runner config* sounds best.

**Comment by bender2k14** [comment]
The [referenced Haskell discussion about seed fixing](https://github.com/hedgehogqa/haskell-hedgehog/issues/201) is motivated by wanting to make CI test runs deterministic.  I have also been bitten by that behavior and would also appreciate that feature (which, as also pointed in that discussion, would be complicated by nightly builds that don't fix the seed).

My stronger motivation however is for rerunning a failed test and having it fail again (for the same reason).  My understanding is that Haskell's Hedgehog achieves that behavior with a feature called [recheck](https://github.com/hedgehogqa/haskell-hedgehog/issues/265#issuecomment-481521259).

Does (the F# version of) Hedgehog have the same `recheck` feature?  I haven't noticed it; I haven't seen any seed or similar message printed when a test fails.  Instead, the message includes all the values that were generated, and I reproduce the failure by copy-pasting all those values into my test code (which is a time-consuming process).

**Comment by moodmosaic** [comment]
There's no `recheck` yet in the .NET version—feel free to add it :+1: You may want to break this in separate steps and/or pull requests, if that's easier for you, e.g.

1. Add `recheck` that runs the test once with a supplied size and seed
2. Print the usage instructions for `recheck` after every test failure
