### ISSUE TITLE
Consider switching to Fable.Mocha

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#197]
>The tests themselves are written once and can run:
> - Inside node.js using Mocha
> - Inside the browser (standalone)
> - Inside a headless browser
> - Inside dotnet with Expecto
> - To Do: Inside dotnet standalone (PR's are welcome)

→ Read more in Fable.Mocha [README](https://github.com/Zaid-Ajaj/Fable.Mocha/blob/d9d232a6e18e2bcfdbe00d30cbb7a18227c0b28d/README.md)
→ Follow the discussion in #196 /cc @ThisFunctionalTom

**Comment by adam-becker** [comment]
Closing as part of merging #196
