### ISSUE TITLE
Add some .NET Framework target

### ISSUE THREAD

**Issue by bender2k14** [hedgehogqa/fsharp-hedgehog#199]
Currently Hedgehog targets only .NET Standard 1.6.
https://github.com/hedgehogqa/fsharp-hedgehog/blob/6d1c5ff8581d9d1bda052e18d256e6469b134ddf/src/Hedgehog/Hedgehog.fsproj#L4

However, only targeting only this version of .NET Standard is problematic.  As Microsoft says in the [documentation for .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard),
> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

In other words, if a user of Hedgehog targets .NET Framework with a version in the interval [4.6.1, 4.7.2), then some runtime problem could occur even when the NuGet restore and build succeed.

There are at least two ways to avoid this problem: one by the consumer and one by the creator.

On the consumer side, a workaround (as included in the above quote) is to target .NET Framework 4.7.2 or greater.  However, a problem with this approach is that it increases the difference between the "production code" and automated testing of that code.  For example, if the production code targets .NET Framework 4.6.1, then it would be more useful for the automated tests to also target 4.6.1.

On the creator side, a workaround is to target both .NET Standard and .NET Framework.  For example, your test dependency [Unqoute](https://www.nuget.org/packages/Unquote/) dual targets [.NET Standard 2.0](https://github.com/SwensenSoftware/unquote/blob/c61b9661bee479e0967a449c5e26f3ab21fd6b84/Unquote.NetStandard/Unquote.NetStandard.fsproj#L4) and [.NET Framework 4.5](https://github.com/SwensenSoftware/unquote/blob/c61b9661bee479e0967a449c5e26f3ab21fd6b84/Unquote/Unquote.fsproj#L12).

I was motivated to create this issue because I encountered a problem today that might have been caused by tests targeting .NET Framework 4.6.1 and depending on Hedgehog that suddenly started failing.  You can read more about that [here](https://github.com/elmish/Elmish.WPF/issues/237).  It might also be of interest that I found a [workaround for this issue](https://github.com/elmish/Elmish.WPF/pull/240) to be replacing `Range.exponential` ~from Hedgehog.Experimental~ with `Range.constant`.

I am willing to help implement dual targeting for Hedgehog.  In a local branch, I quickly verified that the code still builds and all tests continue to pass when targeting .NET Framework 4.6.1.  I also started running the benchmarks but didn't wait for them to finish.

**Comment by cmeeren** [comment]
> It might also be of interest that I found a [workaround of this issue](https://github.com/elmish/Elmish.WPF/pull/240) to be replacing `Range.exponential` from Hedgehog.Experimental with `Range.constant`.

These `Range` functions are from Hedgehog, not Hedgehog.Experimental.

**Comment by moodmosaic** [comment]
Thank you for reporting this, @bender2k14 :100: :+1:

Could we target both .NET Standard and .NET Framework using the plural `TargetFrameworks` element instead?

```diff
- <TargetFramework>netstandard1.6</TargetFramework>
+ <TargetFrameworks>netstandard1.6;net472</TargetFrameworks>

**Comment by moodmosaic** [comment]
>I am willing to help implement dual targeting for Hedgehog.

You're more than welcome :+1:

**Comment by bender2k14** [comment]
> Could we target both .NET Standard and .NET Framework using the plural `TargetFrameworks` element?
> ```<TargetFrameworks>netstandard1.6;net472</TargetFrameworks> ```

Exactly.  As I am sure you know though, the idea is to pick the least recent target that works (so more like `net461` than `net472`).

> It might also be of interest that I found a [workaround for this issue](https://github.com/elmish/Elmish.WPF/pull/240) to be replacing `Range.exponential` with `Range.constant`.

I also determined that [another workaround](https://github.com/elmish/Elmish.WPF/issues/237#issuecomment-652410369) is to use version 3.1.105 instead of version 3.1.301 of the .NET Core SDK.

P.S.
What is the markdown syntax you used to to describe a line deletion and a line addition?  I don't see anything about that in [GitHub's markdown documentation](https://guides.github.com/features/mastering-markdown/).

**Comment by cmeeren** [comment]
> P.S.
> What is the markdown syntax you used to to describe a line deletion and a line addition? I don't see anything about that in [GitHub's markdown documentation](https://guides.github.com/features/mastering-markdown/).

Click the dots on the comment you want to inspect and choose "Quote reply", then you can see the entire "source" for the comment.

**Comment by bender2k14** [comment]
A closely related idea is to also target .NET Standard 2.0 since `FSharp.Core` 4.7.x doesn't support .NET Standard 1.6.

**Comment by bender2k14** [comment]
> A closely related idea is to also target .NET Standard 2.0 since FSharp.Core 4.7.x doesn't support .NET Standard 1.6.

Wait.  On second thought, I think my reasoning there is wrong.

**Comment by cmeeren** [comment]
I think it's generally recommended to target .NET Standard 2.0 even if you target .NET Standard 1.6, because there were a lot of changes between them. For example, dependencies for .NET Standard 1.6 might not be relevant for .NET Standard 2.0.

**Comment by moodmosaic** [comment]
Can't we multi-target all as in https://github.com/hedgehogqa/fsharp-hedgehog/issues/199#issuecomment-652252344? Otherwise I'm fine bumping the version to 2.0.

**Comment by bender2k14** [comment]
Yep.  That multi-targeting should work.

**Comment by moodmosaic** [comment]
Cool! Care to send a PR? 😃 Otherwise I can do on Monday...

**Comment by bender2k14** [comment]
Yes, I can do it.  I feel more confident now that all tests are passing for me :)

**Comment by bender2k14** [comment]
How does a new NuGet package get released?

**Comment by moodmosaic** [comment]
:eyes: It's (currently) a manual process done from my local machine. (Same for the Haskell one, too.) We're a fairly slow moving project. There will be a new NuGet package with all the latest changes, though, soon.

**Comment by moodmosaic** [comment]
Perhaps, with some kind of 'build rule' by saying when version is bumped then go and do a release on NuGet
https://github.com/hedgehogqa/fsharp-hedgehog/blob/07d71bffcfdcf9cb4b2fca3f7a2a297f9afb33cc/src/Hedgehog/Hedgehog.fsproj#L5

**Comment by bender2k14** [comment]
I am most impressed by the release pipelines that are triggered by pushing a tag that matches a certain pattern and contains the desired version number.

That version number in your project file can probably be specified as an argument to the package command.  That would be easier for the tag-initiated process instead needing to change the version number in a commit.

I have never created or used such a release process myself though.

**Comment by moodmosaic** [comment]
>I am most impressed by the release pipelines that are triggered by pushing a tag that matches a certain pattern and contains the desired version number.

Yep, that might work in the F#/.NET version

```
→ git tag -a
→ Push tag
→ Create package
    (implies Hedgehog.fsproj version bump)
→ Push package
```

---

In the Haskell version the process is a bit more involved

```
→ Update CHANGELOG
    (open PR)
→ Create package 
    (implies hedgehog.cabal version bump)
→ Push package _candidate_
    (download and test locally)
→ Push package
→ Update CHANGELOG
    (merge PR)
→ git tag -a
→ Push tag
```

**Comment by bender2k14** [comment]
Do you also want to update a change log in the F#/.NET version?  I always forget about that step.

**Comment by moodmosaic** [comment]
Yep, go ahead :+1: IIRC, next release will be 0.8.*4* as there aren't any breaking changes. I always do that just before a release, e.g. https://github.com/hedgehogqa/fsharp-hedgehog/pull/188

It's also a nice idea to automate the NuGet Package creation by triggering a GitHub Action by pushing a tag, but that can always be done separately.

**Comment by bender2k14** [comment]
> Yep, go ahead 👍 IIRC, next release will be 0.8._4_ as there aren't any breaking changes. I always do that just before a release, e.g. #188

None of the changes I made are breaking (and some are "fixing"! ;) ).  PR #214 is up.

> It's also a nice idea to automate the NuGet Package creation by triggering a GitHub Action by pushing a tag, but that can always be done separately.

I created issue #215 to track this work.
