### ISSUE TITLE
Show status of Travis CI in PR

### ISSUE THREAD

**Issue by bender2k14** [hedgehogqa/fsharp-hedgehog#203]
This is a spinoff of #201 (starting with https://github.com/hedgehogqa/fsharp-hedgehog/issues/201#issuecomment-653214960).

[Travis CI is already configured](https://travis-ci.org/github/hedgehogqa/fsharp-hedgehog) to automatically build the branch of a PR when the PR is created.  It would be useful if the status of this build where displayed in the PR.  It would look something like this:
![Status of Travis CI build in GitHub PR](https://blog.travis-ci.com/images/github-checks-on-pr-conversation.png).

On the GitHub side, it seems to me like the ability to have the status of a build displayed in a PR is possible because of a feature called [GitHub Checks](https://developer.github.com/v3/checks/).  Here is where [Travis CI announced support for GitHub Checks](https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com).

@moodmosaic, is that enough information so that you can easily get the status of the Travis CI build displayed in PRs?  If not, please feel free to delegate something to me, and I will do my best to help.

**Comment by moodmosaic** [comment]
Thanks @bender2k14! Let me check first with @jacobstanley as he setup Travis CI.

**Comment by moodmosaic** [comment]
We just checked with @jacobstanley and for the Haskell repo this just works out of the box. E.g. here's the latest merged PR https://github.com/hedgehogqa/haskell-hedgehog/pull/390 Unsure why this isn't the case for .NET?

**Comment by moodmosaic** [comment]
I can see the status showing up in https://github.com/hedgehogqa/fsharp-hedgehog/pull/208 now.

**Comment by bender2k14** [comment]
I noticed that.  It shows up when it fails.  The goal is to link to the build whether in progressed, passed, or failed.  Here is how it looks for [this passed Elmish.WPF PR](https://github.com/elmish/Elmish.WPF/pull/198), which uses AppVeyor.

![2020-07-08_10-39-12_158_chrome](https://user-images.githubusercontent.com/34664007/86939665-76c86d80-c107-11ea-9022-3158aca9fac2.png)
![2020-07-08_10-39-16_159_chrome](https://user-images.githubusercontent.com/34664007/86939670-79c35e00-c107-11ea-8918-56c5cce5b372.png)

**Comment by moodmosaic** [comment]
Yep, that's clear :+1: I'm just wondering why it won't work out of the box like it did in the Haskell repo :confused:

**Comment by bender2k14** [comment]
After I removed the "draft" status from PR #207, the inprogress status of the automated build showed up.  Maybe this issue is really just that GitHub doesn't show the status if the PR is a draft.

![2020-07-08_15-54-33_160_chrome](https://user-images.githubusercontent.com/34664007/86970735-7b0b7f80-c135-11ea-897b-858de70c16fb.png)

**Comment by moodmosaic** [comment]
Yeah, maybe it does that so we don't hammer the CI. I guess we can close the issue. We can keep the discussion open, of course, and even reopen it, if needed.

**Comment by bender2k14** [comment]
Sounds good
