### ISSUE TITLE
Add target .NET Standard 2.0

### ISSUE THREAD

**Issue by bender2k14** [hedgehogqa/fsharp-hedgehog#204]
This is a spinoff of issue #199 

As pointed out in https://github.com/hedgehogqa/fsharp-hedgehog/issues/199#issuecomment-653670228, one advantage of targeting .NET Standard 2.0 even when also targeting .NET Standard 1.6 is because there can be fewer dependencies for users that are able to consume the version that targets .NET Standard 2.0.

**Comment by moodmosaic** [comment]
👍

**Comment by moodmosaic** [comment]
I don't think it'll be catastrophic if we drop 1.6 entirely. This can be also an intermediate step, where we can have all merged and then focus on #206.

**Comment by bender2k14** [comment]
I would prefer to come back to this after #206 as been resolved.

**Comment by moodmosaic** [comment]
Sure, vice-versa should work as well.

**Comment by moodmosaic** [comment]
Should we close this in favor of #199?

**Comment by bender2k14** [comment]
No, both are helpful.  If a Hedgehog user wants to the latest .NET Core version, then they would prefer to consume a version of Hedgehog built against .NET Standard 2.0 instead of 1.6.  Any addition .NET Framework targets by Hedgehog are irrelevant to them.
