### ISSUE TITLE
Value diffs

### ISSUE THREAD

**Issue by bender2k14** [hedgehogqa/fsharp-hedgehog#211]
This [talk about Haskell's Hedgehog](https://youtu.be/AIv_9T0xKEo?t=1657) (only need to watch from that starting point for 30 seconds) mentions "value diffs".  When some equality expression is false, instead of printing both sides separately, they are printed together except with diff notation to highlight the difference.  Here is a screenshot from that talk.

![2020-07-15_08-25-49_179](https://user-images.githubusercontent.com/34664007/87550907-34f27680-c675-11ea-8432-20b941f90575.png)

Does this concept exist in F# Hedgehog?

**Comment by moodmosaic** [comment]
No, that doesn't exist, and the 'closest' you can get is by using https://github.com/SwensenSoftware/unquote for your assertions.

**Comment by bender2k14** [comment]
Yes.  I use unquote and like it.  I will ask there if they have any thoughts about value diffs.
