### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#215]
This is a spinoff of https://github.com/hedgehogqa/fsharp-hedgehog/issues/199#issuecomment-663945468

> It's also a nice idea to automate the NuGet Package creation by triggering a GitHub Action by pushing a tag...

I never done this before but am excited to do so.

One thing I need from you is to encrypt your NuGet.org API key as a [GitHub secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets).

I will test the YAML file before creating a PR by creating my own package on NuGet.org.

**Comment by moodmosaic** [comment]
> One thing I need from you is to encrypt your NuGet.org API key as a [GitHub secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets).

Sure, I'm planning to look into it during the week.

**Comment by bender2k14** [comment]
No rush.  I mostly wanted to put that link in a comment for future reference.  You don't need to do anything until I have written and tested the YAML.

**Comment by TysonMN** [comment]
My current idea is to have two build actions triggered by a commit into `master` with message matching the pattern `Release x.y.z`.
1. The commit with that message is tagged `vx.y.z`.  (For example, `v0.8.4` like the existing tags.)
2. The NuGet package corresponding to that commit is published as version x.y.z.

**Comment by TysonMN** [comment]
Also, to do this with GitHub Actions

**Comment by moodmosaic** [comment]
Sounds good 👍

**Comment by adam-becker** [comment]
> My current idea is to have two build actions triggered by a commit into `master` with message matching the pattern `Release x.y.z`.
> 
>     1. The commit with that message is tagged `vx.y.z`.  (For example, `v0.8.4` like the existing tags.)
> 
>     2. The NuGet package corresponding to that commit is published as version x.y.z.

I think it would be easier/better to trigger the same actions when a tag is pushed.

Is there a pre-configured [secret][1] for the `NuGet.org` deploy key? The name of that secret will be needed to automate the deployment.

[1]: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

**Comment by TysonMN** [comment]
Triggering on a tag push is also very good.

@moodmosaic can get the secret ser up if it is not already the case.

For testing, I have found it useful to use my fork and push packages to the local feed that each GitHub repo has.

**Comment by moodmosaic** [comment]
Great work! 🚀 v0.10.0 was published on NuGet Gallery automatically (and a v0.10.0 tag was created also).
