### ISSUE TITLE
Documentation of generator for list of int appears wrong

### ISSUE THREAD

**Issue by snuup** [hedgehogqa/fsharp-hedgehog#216]
The docu appears wrong:

    A generator for lists of integers
    Values for xs need to be generated by a generator, as shown in the Generators sections. The following one is for lists of type integer:
    let g = Gen.list (Range.linear 0 100) Gen.alpha;;

This is a Gen < List < char >> .

I guess 

    Gen.list (Range.linear 0 20) (Gen.int <| Range.constant 0 100)

idiomatically defines a  `Gen<List<int>>`.

**Comment by moodmosaic** [comment]
FWIW, this week I'm travelling but I should be able to get to this during weekend, the earliest. Perhaps @jacobstanley can take a look in the meantime.

**Comment by moodmosaic** [comment]
Feel free to submit a pull request to fix this :eyes: FTR, I wrote these docs before we even come up with the notion of *range* so probably after we added `Range` I missed a few spots here and there.

I should be able to update the docs myself during the next couple of days if you don't wish to send a pull request. Thanks :eyes: :+1:

**Comment by moodmosaic** [comment]
@snuup, I've opened https://github.com/hedgehogqa/fsharp-hedgehog/pull/232, let me know if it looks good to you.

**Comment by adam-becker** [comment]
Shouldn't this be closed since the PR to fix the issue was merged?

**Comment by moodmosaic** [comment]
Good catch 👀 Thanks @adam-becker 🍻
