### ISSUE TITLE
Gen.list fails when lower bound is > 0

### ISSUE THREAD

**Issue by snuup** [hedgehogqa/fsharp-hedgehog#217]
I fear this is a bug:

https://stackoverflow.com/questions/64109366/how-can-i-define-a-generator-in-hedgehog-that-generates-lists-of-certain-length

     Gen.list (Range.linear 10 20) (Gen.int <| Range.constant 0 5) |> Gen.printSample

fails when generating shrinked values. It only works for lists with lower bound 0. 
Also generator documentation could be enhanced,

---
Maybe in Gen.fs it should be like

    let private atLeast (n : int) (xs : List<'a>) : bool =
        let nn = min (n - 1) xs.Length
        n = 0 || not (List.isEmpty (List.skip nn xs))

**Comment by moodmosaic** [comment]
FWIW, this week I'm travelling but I should be able to get to this during weekend, the earliest. Perhaps @jacobstanley can take a look in the meantime.

**Comment by moodmosaic** [comment]
Thanks for reporting this :+1: It is a bug. Feel free to send a pull request otherwise I can do also myself over the next few days:

```diff
@@ -336,11 +336,11 @@ module Gen =
                 2, constant None
                 1 + n, map Some g
             ]
 
     let private atLeast (n : int) (xs : List<'a>) : bool =
-        n = 0 || not (List.isEmpty (List.skip (n - 1) xs))
+        n = 0 || not (List.isEmpty (List.skip (min (n - 1) xs.Length) xs))
 
     /// Generates a list using a 'Range' to determine the length.
     [<CompiledName("List")>]
     let list (range : Range<int>) (g : Gen<'a>) : Gen<List<'a>> =
         ofRandom
```

**Comment by snuup** [comment]
I think it should be

    let atLeast (n : int) (xs : List<'a>) : bool =
        xs.Length >= n

I 'm at a hacking level in this repo, think its better you decide and commit the final change.

**Comment by adam-becker** [comment]
> I think it should be
> 
> ```
> let atLeast (n : int) (xs : List<'a>) : bool =
>     xs.Length >= n
> ```
> 
> I 'm at a hacking level in this repo, think its better you decide and commit the final change.

It would appear you are correct:

```fsharp
Property.checkBool <| property {
  let! n = Gen.int (Range.linear 0 100_000)
  let! xs = Gen.list (Range.linear 0 100_000) (Gen.int (Range.linearBounded()))

  let cond1 = n = 0 || not (List.isEmpty (List.skip (min (n - 1) xs.Length) xs))
  let cond2 = xs.Length >= n
  cond1 = cond2
}
```

**Comment by moodmosaic** [comment]
Thanks for the help, @snuup and @adam-becker. 💯
