### ISSUE TITLE
printTree function

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#227]
Haskell Hedgehog has a function [`printTree`](https://github.com/hedgehogqa/haskell-hedgehog/search?q=printTree) that can print trees of generators [like this](https://github.com/hedgehogqa/haskell-hedgehog/pull/406#issuecomment-709275941).  I think such a function would help me in debugging issue #224.  However, just like issue #226, I would prefer if this was a function that returned this tree as a string instead of directly printing it.

Can a `Gen.printTree` or `Gen.treeToString` function be added to F# Hedgehog?

**Comment by TysonMN** [comment]
The tree in https://github.com/hedgehogqa/fsharp-hedgehog/issues/224#issuecomment-724177320 was created after removing
https://github.com/hedgehogqa/fsharp-hedgehog/blob/06bb61ec3882282386751ac107e54195ed220c8c/src/Hedgehog/Tree.fs#L107

I added that line because it matches the behavior in the corresponding Haskell function, which includes a space at the beginning of the four string literals on these [two](https://github.com/hedgehogqa/haskell-hedgehog/blob/7030059c089b45429c9ed23f37971e1b5334dc2e/hedgehog/src/Hedgehog/Internal/Tree.hs#L700) [lines](https://github.com/hedgehogqa/haskell-hedgehog/blob/7030059c089b45429c9ed23f37971e1b5334dc2e/hedgehog/src/Hedgehog/Internal/Tree.hs#L706).

I am not so familiar with the details of Haskell.  Looking at some [example trees](https://github.com/hedgehogqa/haskell-hedgehog/pull/406#issuecomment-709275941) rendered by the Haskell code, it seems to me that Haskell puts the double quotes around a string when showing it.  Whatever the reason, this extra space character looks good when the values in the tree start with an extra character (like a double quote character).

In my trees printed by the F# code, the values do not start with an extra character, so it looks better without this extra space character.

**Comment by TysonMN** [comment]
Here is a comparison.  The current behavior is on the left.  Dropping the extra space (by removing line 107) is on the right.  I think the current behavior matches the corresponding behavior in the Haskell codebase.  In all four cases, `Tree.map (sprintf "%A")` was called.  On the top, the tree contained numbers represented via the type `string`.  On the bottom, the tree contained numbers represented via the type `int`.

```
"0"          "0"
 ├-"1"       ├-"1"
 |  ├-"4"    | ├-"4"
 |  ├-"5"    | ├-"5"
 |  └-"6"    | └-"6"
 ├-"2"       ├-"2"
 |  ├-"7"    | ├-"7"
 |  ├-"8"    | ├-"8"
 |  └-"9"    | └-"9"
 └-"3"       └-"3"
    ├-"10"     ├-"10"
    ├-"11"     ├-"11"
    └-"12"     └-"12"
    
0            0
 ├-1         ├-1
 |  ├-4      | ├-4
 |  ├-5      | ├-5
 |  └-6      | └-6
 ├-2         ├-2
 |  ├-7      | ├-7
 |  ├-8      | ├-8
 |  └-9      | └-9
 └-3         └-3
    ├-10       ├-10
    ├-11       ├-11
    └-12       └-12
```

**Comment by moodmosaic** [comment]
For things in quotes, perhaps the upper left looks better, though for numbers the lower right. FWIW, in Haskell you'll find [fancy unicode characters](https://github.com/hedgehogqa/haskell-hedgehog/blob/7030059c089b45429c9ed23f37971e1b5334dc2e/hedgehog/src/Hedgehog/Internal/Tree.hs#L700-L706) for these, e.g. └╼ ├╼  │

**Comment by TysonMN** [comment]
I think the goal of a render function like this is the make most cases look good enough.  In that sense, I think a reasonable objective is to minimizing the ugliness of the worst case.  I think the bottom-left is uglier than the top-right, so I would prefer to remove the extra space for all cases.

Would you approve a PR in which I remove the addition of that extra space on line107?

I tried copy pasting those characters from the Haskell codebase, but they didn't look good when printed on my computer.  Certainly I am open to someone finding better characters for .NET.

**Comment by moodmosaic** [comment]
That PR would be welcome! Yep, let's do that :+1:
