### ISSUE TITLE
Unable to compile with Fable

### ISSUE THREAD

**Issue by adam-becker** [hedgehogqa/fsharp-hedgehog#248]
When compiling `Hedgehog.fsproj` with Fable, I see around 500 of these:

```
ERROR in ./Tests.fs
Module Error (from ./node_modules/fable-loader/index.js):
/workspaces/fsharp-hedgehog/src/Hedgehog/Numeric.fs(276,8): (276,49) error FABLE: Cannot resolve locally inlined value: call_2 - Inline call from .(293,8) < ./Range.fs(188,16) < ./Range.fs(220,27) < ./Range.fs(369,8) < ../../tests/Hedgehog.Fable.Tests/Tests.fs(9,26)
```

Seems to be an issue with inlining the functions defined in `Numeric.fs`. I was trying to revive #196 and ran into this.

**Comment by moodmosaic** [comment]
Interesting. I think we were all set with Fable. Perhaps one of the recent PRs broke something(?)

>When compiling Hedgehog.fsproj with Fable, I see around 500 of these:

What's the command you're using to do this?

**Comment by TysonMN** [comment]
Seems we should add a Fable compilation step to the CI process.

**Comment by adam-becker** [comment]
> What's the command you're using to do this?

@moodmosaic I had just run through the "getting started with Fable.Tests" documentation, so the command was `npm run-script test`, which ran the project through `fable-splitter`, and at that point I lose the thread. But I don't think I was doing anything outside the recommended approach.

I could try and pull #196 directly and see if that still builds.

> Seems we should add a Fable compilation step to the CI process.

@TysonMN I agree, if we're going to have Fable support we should probably check that it continues to work. That could probably be part of the larger "automate deployments" work that needs to be done.

**Comment by adam-becker** [comment]
I pulled #196 and rebased on the latest master, it still works so now I'm unsure where I went wrong. But this doesn't appear to be an issue with the project.

Chalk this up to the old PEBCAK.
