### ISSUE TITLE
Generate single/float32

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#249]
I noticed the auto-generator in Hegehog.Experimental failing for one of my record types. It was because it couldn't generate a `single` (`float32`) property. When I tried to add support for it to the auto-generator, I discovered that Hedgehog has no `Gen.single`. Can this be added?

In the meantine, is there any downside to doing this in the auto-generator? (Or if you can implement `Gen.single` quickly, I can wait.)

```f#
Gen.float (Range.exponentialFrom 0. (float Single.MinValue) (float Single.MaxValue)) |> Gen.map single
```

**Comment by moodmosaic** [comment]
Feel free to send a PR. We're about to cut a release soon so probably we can include it in.

**Comment by cmeeren** [comment]
Is the implementation above fine? Otherwise I wouldn't know how to implement it.

In any case, I have no personal need to have my name on the commit - I may have some time during the weekend, but if you're in the codebase before that, feel free to just add it.

**Comment by cmeeren** [comment]
Might also consider adding a corresponding `Gen.decimal` at the same time:

```f#
Gen.double <| (Range.exponentialFrom 0. (float Decimal.MinValue) (float Decimal.MaxValue)) |> Gen.map decimal
```

**Comment by moodmosaic** [comment]
Let's add just single and if it's efficient enough then we can add decimal if that's OK.

**Comment by cmeeren** [comment]
Ok, I will need the workaround in the auto-generator anyway then. Is there any reason why we can't add `decimal` too, and just improve it if it turns out not to be good enough?

By the way, I wasn't thinking of performance (AFAIK the performance of the implementations I posted won't be prohibitive compared to the existing `double` since it's just a `double` and a map to `single`/`decimal`). I was more concerned about any correctness issues (though I can't see any).

**Comment by moodmosaic** [comment]
Just a quick thought... Couldn't we implement decimal with the help of Gen.double? Perhaps similar for single.

**Comment by cmeeren** [comment]
Isn't that exactly what I have proposed?

**Comment by moodmosaic** [comment]
I can't tell much as I'm out and about at the moment. If it was, then 👍

**Comment by cmeeren** [comment]
@moodmosaic Do you know when you plan to release?

**Comment by moodmosaic** [comment]
@cmeeren, I've released Haskell yesterday, as all PRs for the release were already merged, and have this release scheduled for coming Tuesday.

This is a rough estimation though, not a deadline, as we haven't automated the releases yet.

If for some reason that estimate won't work for you, perhaps you can help.

All we need is a PR similar to #214, a tag, and creare & push on NuGet.

**Comment by cmeeren** [comment]
Thanks. I have no problems waiting until next week.
