### ISSUE TITLE
Documentation from NuGet package

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#254]
I expected PR #251 to bring documentation to the tooltips in Visual Studio when consuming Hedgehog via NuGet package.  I locally created a NuGet package (thanks to PR #253) and added it to a project, but I still don't see the documentation.  I was talking with @dharmaturtle, and he has the same behavior.

@cmeeren, do you see the documentation in tooltips from a locally created NuGet package?

**Comment by cmeeren** [comment]
How did you add it to the project? If you did not bump the version, you must ensure that you remove the old cached Hedgehog version from your global NuGet cache, otherwise it's the existing cached version that gets restored.

**Comment by cmeeren** [comment]
> If you did not bump the version, you must ensure that you remove the old cached Hedgehog version from your global NuGet cache, otherwise it's the existing cached version that gets restored.

Also, I think you must clean your project if you had already installed Hedgehog, otherwise it won't install/restore anything (since it is already restored).

**Comment by dharmaturtle** [comment]
Here's where you can add a new package source in VS (Tools > Options):

![image](https://user-images.githubusercontent.com/1278803/102028680-f91d2380-3d70-11eb-9881-0a99b496810c.png)

As you can see I bumped the version to `0.8.555`. I also tested with `0.8.5`.

Docs don't appear for `Range.exponentaial` for me, though they _do_ appear for the __ prefixed methods below it (e.g. `__exponentialBoundedDecimal`).

![image](https://user-images.githubusercontent.com/1278803/102028779-6af56d00-3d71-11eb-9376-de972c43c815.png)

Note the package source in the upper right corner.

**Comment by dharmaturtle** [comment]
Ah, this is due to the fact that we're pretending `-` to the `CompiledName`.

![image](https://user-images.githubusercontent.com/1278803/102029994-7a2ae980-3d76-11eb-9e2e-fa03bb769e26.png)

**Comment by TysonMN** [comment]
Excellent work @dharmaturtle!

@moodmosaic, what is the purpose for `-` in compiled names?

**Comment by dharmaturtle** [comment]
@TysonMN https://github.com/hedgehogqa/fsharp-hedgehog/pull/219

**Comment by cmeeren** [comment]
What's the purpose of all the `__`-prefixed stuff? If it is intended as implementation details, but has to be public due to being used in `inline` code, then it's much better to annotate it with `[<EditorBrowsable(EditorBrowsableState.Never)>]` (requires `open System.ComponentModel`).

**Comment by moodmosaic** [comment]
>What's the purpose of all the `__`-prefixed stuff?

It turns out that those can't be used outside F#, so we try to 'hide' them from IntelliSense:  https://github.com/hedgehogqa/fsharp-hedgehog/issues/156#issuecomment-702977269

>to annotate it with `[<EditorBrowsable(EditorBrowsableState.Never)>]` (requires `open System.ComponentModel`).

I've tried that, of course, but then they were hidden also from inside F#'s IntelliSense: https://github.com/hedgehogqa/fsharp-hedgehog/issues/156#issuecomment-703212887

**Comment by moodmosaic** [comment]
@TysonMN, @dharmaturtle, @cmeeren, if they are causing some unexpected behavior, now it's time to do something for it, before cutting a release. Though, I (and I believe also @mausch) couldn't see anything unusual in Rider.

**Comment by dharmaturtle** [comment]
Changing the `-` to a backtick ( `` ` ``) resolves this issue for Visual Studio:

![image](https://user-images.githubusercontent.com/1278803/102150757-eff68a00-3e36-11eb-9dbe-d3429f6ef16d.png)

`Exponential` is still hidden from C#:

![image](https://user-images.githubusercontent.com/1278803/102150784-fe44a600-3e36-11eb-8c15-05f642f58d6f.png)

And still works for Rider:

![image](https://user-images.githubusercontent.com/1278803/102150856-292efa00-3e37-11eb-9dd3-44b76970a470.png)

I can make a PR for this if yall like this solution.

**Comment by moodmosaic** [comment]
Awesome! Go for it, @dharmaturtle 🎸

**Comment by moodmosaic** [comment]
@cmeeren, are you fine waiting for a PR by @dharmaturtle? Might push v0.9.0 release to Wednesday or Thursday.

**Comment by cmeeren** [comment]
That's fine with me, I'm in no hurry.
