### ISSUE TITLE
Investigate Fantomas for consistent formatting

### ISSUE THREAD

**Issue by adam-becker** [hedgehogqa/fsharp-hedgehog#271]
Issues with formatting/style have cropped up a few times in PRs, so we might want to look into using an auto-formatting tool. Fantomas appears to be the front runner in this domain.

I'm curious what other members think (as well as contributors, of course). /cc @moodmosaic @TysonMN

**Comment by moodmosaic** [comment]
I'd be surprised if Fantomas could handle this particular formatting/style. I'm all in for this, though, unless Tyson has a different opinion.

**Comment by TysonMN** [comment]
When programming in C#, I am satisfied with the amount of `.editorconfig` settings supported by Visual Studio.  For F#, Visual Studio only supports a few settings, and I have not felt the need to in my F# programming to find an automated solution to enforce additional settings.

Even so, I still like having automated solutions for such things, so I am in too.

I have my preferences about formatting, but I care much more that the formatting is consistent.

I just created PR #273, which adds a `.editorconfig` file.

**Comment by moodmosaic** [comment]
An alternative can be just a markdown file explaining what the style is, similar to https://github.com/hedgehogqa/haskell-hedgehog/blob/master/STYLE_GUIDE.md

**Comment by dharmaturtle** [comment]
Both [Fantomas](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_space_before_colon) and [FSharpLint](https://fsprojects.github.io/FSharpLint/reference/FSharpLint.Core/fsharplint-rules-typeditemspacing.html) support spaces before/after colons, which I believe was the instigating issue.

**Comment by adam-becker** [comment]
Generally I think formatting tools go too far, and/or have less tolerance for certain things. I tried running [Fantomas][fantomas-live] on the `Gen.fs` file, and the results seemed sporadic, like `Gen (fun x -> ...` would be split across multiple lines sometimes but wouldn't be in other situations.

Another issue is that most of the code I've seen in this repo has a function body on a new line, whereas Fantomas will only do that for "complex" expressions, or expressions that are less then `n` characters. If the tool were "dumber" and just always formatted the code a certain way, I'd have a better feeling about it. I feel like they've gone to great lengths to make the tool more flexible in it's output rules, but in doing so it makes the formatted code artifact look frantic.

[fantomas-live]: https://fsprojects.github.io/fantomas-tools/#/fantomas/preview

**Comment by moodmosaic** [comment]
>and the results seemed sporadic

...which is one of the reasons you don't see `.stylish-haskell.yaml` in haskell-hedgehog either. It's tricky, and usually not worth the effort unless it's a fairly sized codebase with many (more than 10-15, IME) *active* contributors.

**Comment by adam-becker** [comment]
Closing in favor of #286, once that's complete we'll have a standard to point to for resolving style issues in PRs.
