### ISSUE TITLE
obj folder displayed in solution

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#278]
The line
https://github.com/hedgehogqa/fsharp-hedgehog/blob/f0ea8a1a35eefd7ae0f5734fdef5eb1d3b75064e/src/Hedgehog/Hedgehog.fsproj#L45
and especially the `**\*.fs` part, causes the `obj` folder to be displayed in the solution.

What is the purpose of this line?  Can it be changed to something else so that the `obj` folder is not displayed in the solution?

**Comment by moodmosaic** [comment]
Perhaps it's an artifact of #194. We shouldn't display it in the solution view, if possible.

**Comment by moodmosaic** [comment]
It was added in https://github.com/hedgehogqa/fsharp-hedgehog/commit/48bffa0cbd0e6d42b99b4c4a23f4dafb52eb7b57#diff-a2849db3ba772628ebb74601ebadb15426e7b6fa066fb8b5b60b48c5eae30db5.

@ThisFunctionalTom we don't really depend on `obj` dir, IIRC, right? If so, we can change `**\*.fs` so that `obj` isn't picked up.

**Comment by adam-becker** [comment]
@moodmosaic We shouldn't depend on the obj dir, if we are then that's a defect worth fixing.

**Comment by ThisFunctionalTom** [comment]
> It was added in [48bffa0#diff-a2849db3ba772628ebb74601ebadb15426e7b6fa066fb8b5b60b48c5eae30db5](https://github.com/hedgehogqa/fsharp-hedgehog/commit/48bffa0cbd0e6d42b99b4c4a23f4dafb52eb7b57#diff-a2849db3ba772628ebb74601ebadb15426e7b6fa066fb8b5b60b48c5eae30db5).
> 
> @ThisFunctionalTom we don't really depend on `obj` dir, IIRC, right? If so, we can change `**\*.fs` so that `obj` isn't picked up.

No, fable does not need obj dir as far as I know. We just need the "normal" hedgehog sources packed in nuget package in fable directory to be "fable compatible". Fable uses this sources then to generate javascript files.

**Comment by moodmosaic** [comment]
Thank you, @ThisFunctionalTom. Then all we neee is a better wildcard pattern to match there.

**Comment by adam-becker** [comment]
Just looked into this, and indeed those `obj` files are sneaking into the nuget package as well. I've experimented with using the `Exclude` attribute but it doesn't seem to do anything, unless I'm doing it wrong.

**Comment by TysonMN** [comment]
Great workvyou two!

**Comment by moodmosaic** [comment]
Thank you @adam-becker and @ThisFunctionalTom, and @TysonMN for raising this! :beers: :+1:
