### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#280]
@adam-becker, @TysonMN, we should be doing a release after merging

* <del>https://github.com/hedgehogqa/fsharp-hedgehog/pull/238</del> *Postponed for 0.11.0 or 1.0.00*
* https://github.com/hedgehogqa/fsharp-hedgehog/pull/247
* https://github.com/hedgehogqa/fsharp-hedgehog/pull/275

I think those are ready to merge, or close to be ready to merge. This way we can get the Hedgehog.Linq stuff out soon. And then focus on the other ones.

**Comment by moodmosaic** [comment]
I believe #238 needs some more review (there are still some comments around tail calls discussions, and some discussions around filtering functions being (re)/moved to Gen module).

Once we get #247 merged we should be good to a 0.10.0 release, if you agree, @adam-becker @TysonMN.

**Comment by TysonMN** [comment]
I am fine with a release at any time.

**Comment by moodmosaic** [comment]
With #288, #196, Hedgehog.Linq and all the other great stuff we've added, v1.0 makes more sense at this point.

**Comment by dharmaturtle** [comment]
If we still want to [include Hedgehog.Experimental in the v1.0](https://github.com/hedgehogqa/fsharp-hedgehog/issues/182), we might consider making v0.10.0 first.

**Comment by TysonMN** [comment]
I agree with @dharmaturtle.  I would prefer `Gen.auto` be moved before v1.0.

**Comment by TysonMN** [comment]
More generally, I am in favor of putting off v1.0 as long as active progress is being made to make (major) improvements.

**Comment by dharmaturtle** [comment]
Agreed with putting off v1.0. Additionally, the fact that we're still introducing breaking changes (e.g. `check'` -> `checkWith`) means the API is not stable yet. Perhaps as we document the public API, we'll realize other changes that need to be made.

**Comment by moodmosaic** [comment]
I was thinking about looking forward v1.0 after a couple of months from now, but yes if we want to release sooner than that then v0.10 makes sense. 👀 👍

**Comment by moodmosaic** [comment]
A few things we can test on next release (v0.10)

* #215, #261 — Release/Package automation
* #277 — Documentation 

It'd be nice to add some release notes, or some more examples in the docs, with all the great stuff we've added:

* #244 — Hedgehog.Linq
* #288 — PropertyConfig
* #266 

And any breaking changes introduced between this release and older releases may as well be included in the notes. — This one can be 'easy' as I can simply upgrade F# Hedgehog on some of the older codebases from a few years ago.

*(These are basically notes to myself, or to those willing to take over or help with maintaining this codebase.)*

**Comment by TysonMN** [comment]
Going forward, I recommend we add to the release notes any new features, breaking changes, and such as part of the process of completing a PR.

**Comment by adam-becker** [comment]
> _(These are basically notes to myself, or to those willing to take over or help with maintaining the ~codebase~ project.)_

@moodmosaic I wouldn't mind helping to maintain the project.

**Comment by moodmosaic** [comment]
@adam-becker I appreciate this, as well as all the great work you're doing. This is great news for the project. :rocket: :100:

**Comment by adam-becker** [comment]
@moodmosaic I've created a `0.10.0` label, and added it to issues I think should be in `0.10.0`, feel free to change that assignment.
