### ISSUE TITLE
Seq module scope

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#306]
I would prefer if the `Seq` module had internal scope.  Currently it has public scope.

https://github.com/hedgehogqa/fsharp-hedgehog/blob/f346f77b40231978e6f7904b67f96b559780d548/src/Hedgehog/Shrink.fs#L3-L17

**Comment by moodmosaic** [comment]
Yes, it ought to be internal. I can't remember why we've declared it as public. Feel free to change it to internal.
