### ISSUE TITLE
A way to render a list completely in the report?

### ISSUE THREAD

**Issue by altxt** [hedgehogqa/fsharp-hedgehog#323]
Given a property that takes a list generator, such as this
```cs
[Test]
public void Hedgehog_List_IsPrintedIncomplete()
{
    var property =
        from xs in Property.ForAll(Gen.Int32(Range.Constant(1, 255)).List(Range.Constant(1, 100)))
        select xs.All(x => x < 255);
    property.Check(PropertyConfig.Default.WithShrinks(0));
}
```
When the property fails, the output only shows the first several elements of the list
```
System.Exception : *** Failed! Falsifiable (after 5 tests):
seq [188; 144; 215; 37; ...]
```
It can be beneficial to be able to see all elements of the list in the test output. This can be achieved by wrapping the input in a class and overriding its ToString(), but it takes significantly more code, so a simpler way would be preferable.
```cs
class Wrapper
{
    public List<int> Xs;

    public override string ToString()
    {
        return $"[{string.Join(", ", Xs)}]";
    }
}

[Test]
public void Hedgehog_ListWithinClassWithACustomToString_IsPrintedComplete()
{
    var gen =
        from xs in Gen.Int32(Range.Constant(1, 255)).List(Range.Constant(1, 100))
        select new Wrapper {Xs = xs};
    var property =
        from wrapper in Property.ForAll(gen)
        select wrapper.Xs.All(x => x < 255);
    property.Check(PropertyConfig.Default.WithShrinks(0));
}
```

**Comment by altxt** [comment]
An equivalent F# test works as expected
```fsharp
testCase "generated input list of five elements is not abbreviated in the report" <| fun _ ->
    Expect.throwsC
        (fun () ->
            property {
                let! xs = Range.singleton 0 |> Gen.int |> Gen.list (Range.singleton 5)
                return Seq.forall ((>) 0) xs
            }
            |> Property.checkWith (PropertyConfig.withShrinks 0<shrinks> PropertyConfig.defaultConfig)
        )
        (fun ex ->
            Expect.isNotMatch ex.Message "\.\.\." "Abbreviation (...) found"
        )
```
But if we convert the F# list to a C# list, like Hedgehog.Linq does, then the ellipsis is there
```
                let! xs = Range.singleton 0 |> Gen.int |> Gen.list (Range.singleton 5) |> Gen.map ResizeArray
```
It looks like `sprintf "%A"` only recognizes a C# generic `List<T>` (aka `ResizeArray<_>`) as IEnumerable (aka seq) but not as a list and so, knowing that it can be infinite or slow to traverse, decides to only dump the first elements.

**Comment by adam-becker** [comment]
@altxt If you have more tests like these, we'd be glad to include them for the C# interface so we don't introduce regressions. C# support is something we definitely want to improve, so these would be a very welcome addition!
