### ISSUE TITLE
A way of generating a smart diff?

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog#325]
`Hedgehog` in Haskell is awesome at generating smart diff when using `===` operator:

![image](https://user-images.githubusercontent.com/1394391/111942872-5ec73b80-8b28-11eb-8828-51d4c5ff97f4.png)

Is there a way of doing it in F#, too?

**Comment by TysonMN** [comment]
Duplicate of #211
