### ISSUE TITLE
Sample from Readme.md for csharp not compiled in 0.10.0 in netstandart2 dll

### ISSUE THREAD

**Issue by lupin-de-mid** [hedgehogqa/fsharp-hedgehog#331]
Method `Gen.String`  not exist in dll in namespace `Hedgehog.Linq`
Checked for  net standart 2.0  and net 4.8

**Comment by lupin-de-mid** [comment]
This line probably should look like
`   var stringGen = GenExtensions.String(Gen.Alpha, Hedgehog.Linq.Range.FromValue(stringLength));`

**Comment by adam-becker** [comment]
Thanks for opening this issue! I also noticed some awkwardness around the `Hedgehog.Linq` namespace, and using Hedgehog from C#. I'm open to ideas on how to make this more ergonomic.
