### ISSUE TITLE
Applicative ListGen.traverse

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#339]
Like PR #338, in preparation for #268, let's implement `ListGen.traverse` applicatively.

**Comment by adam-becker** [comment]
I think the remaining work around #268 is going to be delayed to `0.12.0`, but I'm in favor of doing this. 💯

**Comment by TysonMN** [comment]
I don't care when these features get released.  I am implementing them because I enjoy the work so much :)

**Comment by adam-becker** [comment]
> I don't care when these features get released. I am implementing them because I enjoy the work so much :)

That's fine, just pointing out that I'm going to start only merging things for 0.11.0 so we can get it out the door. At some point our users need to get their hands on all of the fun things you make :)

**Comment by TysonMN** [comment]
This is included in [version 0.12.1](https://www.nuget.org/packages/Hedgehog/0.12.1).
