### ISSUE TITLE
"where" after definition but before use marks identifier as unused

### ISSUE THREAD

**Issue by the-not-mad-psychologist** [hedgehogqa/fsharp-hedgehog#410]
In this code sample, both JetBrains Rider and Visual Studio mark `i` as unused.

```F#
let ``removeAt reduces length by one for non-empty lists`` () =
  property {
    let! s = GenX.auto<int list>
    let! i = List.length s - 1 |> Range.constant 0 |> Gen.int // Error: The value 'i' is unused
    where (s <> List.empty)
    return List.length s - 1 = (List.removeAt i s |> List.length)
  }
  |> Property.check
```

If we define `i` after the `where`, though, no error is shown.

```F#
let ``removeAt reduces length by one for non-empty lists`` () =
  property {
    let! s = GenX.auto<int list>
    where (s <> List.empty)
    let! i = List.length s - 1 |> Range.constant 0 |> Gen.int
    return List.length s - 1 = (List.removeAt i s |> List.length)
  }
  |> Property.check
```

**Comment by TysonMN** [comment]
Your first code block has two `where`s. Is that a typo?

**Comment by the-not-mad-psychologist** [comment]
@TysonMN Corrected, thank you!

**Comment by TysonMN** [comment]
Can you try to simplify this to a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by the-not-mad-psychologist** [comment]
@TysonMN Fair enough. How is this?

```F#
let identityProperty =
  property {
    let! i = GenX.auto<int> // The value 'i' is unused
    where true
    return i = i
  }
```

**Comment by TysonMN** [comment]
Is it also reported as unused if `where true` is replaced by `where false`?

**Comment by the-not-mad-psychologist** [comment]
> Is it also reported as unused if `where true` is replaced by `where false`?

It is.

**Comment by TysonMN** [comment]
Can you check if this also happens with the `seq` CE?  If it does, then the problem has nothing to do with F# Hedgehog.

**Comment by the-not-mad-psychologist** [comment]
Pardon. Does `seq` have a `where` keyword?

**Comment by TysonMN** [comment]
The `seq` type has `where` semantics, so I was assuming that it's CE would have that syntax, but my assumption could be wrong.  Are you saying that it lacks a `where` keyword?

**Comment by the-not-mad-psychologist** [comment]
I'm saying that, if it exists, I can find no documentation for it. Also:
```F#
let foo =
  seq {
    where true // The value or constructor 'where' is not defined.
  }
```

**Comment by TysonMN** [comment]
I should have checked this first... `where` is a custom keyword in our `property` CE:
https://github.com/hedgehogqa/fsharp-hedgehog/blob/d9b0e7eacef9b41d0a95289cf273d12f995c66a9/src/Hedgehog/Property.fs#L351-L353

**Comment by TysonMN** [comment]
I don't think this issue is caused by F# Hedgehog.  I am using...

> Microsoft Visual Studio Enterprise 2019
> Version 16.11.14

...and don't have that problem.

![2022-05-14_20-52-04_705_devenv](https://user-images.githubusercontent.com/34664007/168453877-4652bcf5-f31b-4998-9bca-2c32fee8d4f2.png)

What IDE (and version) are you using?

That screenshot shows this test...

```fsharp
let identityProperty =
  property {
    let! i = Gen.alpha // The value 'i' is unused
    where true
    return i = i
  }
```

...which is more minimal that yours because `GenX` is defined in [`fsharp-hedgehog-experimental`](https://github.com/hedgehogqa/fsharp-hedgehog-experimental) while `Gen.alpha` is defined here in F# Hedgehog.

**Comment by TysonMN** [comment]
Nevermind, I do have this problem.  I think I needed to turn on warnings for unused values first ([like this](https://github.com/elmish/Elmish.WPF/blob/a35898abf2ac3d5fc33b9eb81de6e6d590a0e1e7/src/Elmish.WPF/Elmish.WPF.fsproj#L24)).

Here is an reproduction that already exists in the F# Hedgehog codebase:
https://github.com/hedgehogqa/fsharp-hedgehog/blob/830ef95cbcd6cdfcec5563f09841fb40371f836c/tests/Hedgehog.Tests/PropertyTests.fs#L44-L49

**Comment by TysonMN** [comment]
To investigate this further, I would next try to reproduce this without involving F# Hedgehog.  Want to give that a try?

**Comment by TysonMN** [comment]
You can start with a CE for the [identity monad](https://blog.ploeh.dk/2022/05/16/the-identity-monad/).

**Comment by the-not-mad-psychologist** [comment]
Okay, here's my clumsy expansion of Mark Seemann's version and its results:
```F#

type Identity<'a> = Identity of 'a

module Identity =
  let bind f (Identity x) : Identity<_> = f x
  let return' = Identity
  let filter _ (a: Identity<'a>) = a

type IdentityBuilder() =
  member _.Bind(x, f) = Identity.bind f x
  member _.Return x = Identity x
  member _.ReturnFrom x = x
  member _.Yield a = Identity.return' a
  member _.While a = a
  member a.For x = a.While x

  [<CustomOperation("where")>]
  member a.Where f i = i |> Identity.filter f

let identity = IdentityBuilder()

let i =
  identity {
    let! x = Identity "corge"
    let! y = Identity 47
    where "foo"
    return y - x.Length // The value or constructor 'y' is not defined. The value, namespace, type or module 'x' is not defined.
  }
```

**Comment by the-not-mad-psychologist** [comment]
This is most strange! Does a custom operation somehow absorb the identifiers defined before it?

**Comment by TysonMN** [comment]
You can simplify your reproduction by inlining `Identity.filter` and `Identity.bind`.  See if you can simplify further by removing any of the CE's methods.  My guess is that you can also simplify the CE use by removing `x`.  Also replace `47` with `0`.

**Comment by the-not-mad-psychologist** [comment]
Here's a simplified version, then.

```F#
type Identity<'a> = Identity of 'a

type IdentityBuilder() =
  member _.Bind(Identity x, f) : Identity<_> = f x
  member _.Return x = Identity x
  member _.Yield x = Identity x
  member _.For x = x

  [<CustomOperation("where")>]
  member _.Where _ x = x

let identity = IdentityBuilder()

let i =
  identity {
    let! x = Identity ""
    where "foo"
    return x // The value, namespace, type or module 'x' is not defined.
  }
```
