### ISSUE TITLE
Recheck runs property multiple times

### ISSUE THREAD

**Issue by dharmaturtle** [hedgehogqa/fsharp-hedgehog#420]
Stealing code from [this issue](https://github.com/hedgehogqa/fsharp-hedgehog/issues/408#issue-1213793030):

```fsharp
    testCase "my test2" <| fun () ->
        property {
            let! i = Gen.int32 (Range.linear 1 10)
            System.Diagnostics.Debugger.Break()
            Expect.isTrue (i <= 5)
        }
        |> Property.recheck "59_15683818216235017248_6890634259096173777_"
```

The breakpoint is hit multiple times. I think Hedgehog is rerunning the shrink runs. The values of `i` in chronological order are as follows: `6, 1, 3, 5`. I'm guessing this isn't expected behavior?

**Comment by dharmaturtle** [comment]
It isn't obvious to me that `reportRecheckWith` should `followShrinkPath`: https://github.com/hedgehogqa/fsharp-hedgehog/blob/b48f662ba42541dd51b0a116cca2489339d14d6a/src/Hedgehog/Property.fs#L250

**Comment by TysonMN** [comment]
I think you need to add `return` on the last line of your CE.  This is a limitation imposed by F#.

Can you check and report back?

**Comment by TysonMN** [comment]
I don't understand your second comment. I will call you later to discuss.

**Comment by dharmaturtle** [comment]
`return Expect.isTrue (i <= 5)` does indeed only run once with `recheck`.

Kinda wish there was some way to make the dev experience on this better.
