### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#45]
Perhaps, it will allow broader reach if we make sure that the F# version can be used with both .NET <del>Core</del>Standard and Mono. ― A quick comparison between Mono and .NET Core can be found [here](https://docs.microsoft.com/en-us/dotnet/articles/core/#comparison-with-mono).

**Comment by jystic** [comment]
It should work with Mono, I've been developing this on a Mac 👍 

But yes, I'd love support for .NET Core

**Comment by moodmosaic** [comment]
Talking about .NET Core, here's a decent FAQ about [what .NET Standard means for .NET Core](https://github.com/dotnet/standard/blob/master/docs/faq.md) and more.

**Comment by moodmosaic** [comment]
.NET Framework 4.7.1 will have built-in support for .NET Standard 2.0. This means that you don't have to deploy any additional files or use binding redirects to use .NET Standard 2.0 libraries.

There's more at: https://github.com/dotnet/announcements/issues/32

**Comment by moodmosaic** [comment]
Some places to look at:

- https://github.com/dotnet/cli/issues/4874
- https://github.com/SwensenSoftware/unquote/pull/136

**Comment by Porges** [comment]
Latest VS now has proper support for this, so it should be much easier.

**Comment by Porges** [comment]
Hedgehog can probably target something lower than 2.0, as well. It doesn't have much interaction with the outside world!

**Comment by moodmosaic** [comment]
Indeed, basically its only external dependency is `System` and `FSharp.Core`.

I'm still not sure what's the proper way of adding support for .NET Standard, other than starting with a new project and copying all files from the old to the new one.

**Comment by cmeeren** [comment]
> starting with a new project and copying all files from the old to the new one.

I think that would be best.

**Comment by Porges** [comment]
See https://github.com/hedgehogqa/fsharp-hedgehog/pull/153 for a first take.

**Comment by moodmosaic** [comment]
I'm closing this, since we've now merged #153.
