### ISSUE TITLE
Shrink README

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#69]
Maybe we should have a more compact README, like [the one in TypeScript](https://github.com/Microsoft/TypeScript/blob/0212319b170e0501b97a50170eb05ad5a4da5fa3/README.md), or similar? I think, right now it's a bit [TL;DR](https://en.wikipedia.org/wiki/TL;DR). Any content that we take out could be moved to specific `docs/Xyz.md` files.

**Comment by jystic** [comment]
Yeah I think that's a good idea 👍
