### ISSUE TITLE
Add the ability to discover and run all properties

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#80]
in a file, or a module<del>, using [Erased Provided Types](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/creating-a-type-provider#details-about-erased-provided-types)</del>.

I haven't thoroughly think about this, but it should act similarly to adding the Template Haskell splice which runs all the properties in Haskell.

**Comment by jystic** [comment]
Yeah that would be pretty cool 👍

**Comment by moodmosaic** [comment]
I've looked into this and I think a TP seems like an overkill. At the end, I might end up just using Reflection.

**Comment by ploeh** [comment]
As a knee-jerk reaction, I think this should be the responsibility of a testing framework/library. If I correctly understand this suggestion, this is what Gerard Meszaros calls _Test Discovery_ in [xUnit Test Patterns](http://bit.ly/xunitpatterns).

Various libraries have different ways they perform test discovery. For example, [xUnit.net](https://xunit.github.io) uses reflection, whereas [Expecto](https://github.com/haf/expecto) uses lists of tests as first-class citizens.

If such a feature was added to Hedgehog, could it still accommodate such divergent approaches by third parties?

**Comment by moodmosaic** [comment]
I've been going back and forth on that one. On one hand, [I agree that test discovery is the responsibility of a testing framework/library](https://twitter.com/search?l=&q=test%20discovery%20from%3Anikosbaxevanis&src=typd) like xUnit.net or Expecto.

On the other hand, I was thinking that, perhaps, the public APIs of the Haskell and F# version ought to be similar (?)

(In fact, that's what we've been doing with `Seed`, `Shrink`, and `Range`, which are modeled closely to Haskell version. This is also the plan for `Tree` and `Gen`, in order to have a solid foundation to work on #110.)

If we go and look [Hedgehog's public API on Hackage](https://hackage.haskell.org/package/hedgehog/docs/Hedgehog.html), at the time of this writing (v4.0.1), we'll notice that test discovery is part of the public API. It's basically for this reason that I've opened this item...

---

Perhaps, we could skip test discovery from the F# version—after all, I assume that most F# Hedgehog users won't be using this tool from command-line, but they'll be using it with Expecto, xUnit.net, or similar.

I *do* like however the pretty printing and diff output of the Haskell version. Should we have something similar with Expecto or xUnit.net, that'd be great.

![](https://user-images.githubusercontent.com/134805/27766416-3ba58288-5f12-11e7-915d-113bf9ad3fc6.png)
![](https://user-images.githubusercontent.com/134805/27515768-9ecd3802-59ee-11e7-8ecf-c86193b38d98.png)

**Comment by ploeh** [comment]
Is it conceivable that, even if the Haskell version has a feature, it could be a mistake?

I don't think this feature belongs in a library like this. I don't think it belongs in a Haskell library, either. Once you can run tests, the next feature users will request is a nice _test run report_ in a file. Not only that, but some will [request a file in a format that works with VSTS](https://github.com/haf/expecto/issues/179), while others will want it to work with Team City, and so on. Where do you draw the line?

What happened to the Unix philosophy of writing programs that do one thing, and do them well?

**Comment by moodmosaic** [comment]
Thank you for pointing to that Expecto issue/example. That's interesting.

>What happened to the Unix philosophy of writing programs that do one thing, and do them well?

Yes, indeed.

I think, with the tools that are already available, like Unquote, and Expecto or xUnit.net, we can do without 'doing' what's described in this issue.
