### ISSUE TITLE
We should probably rename this to fsharp-hedgehog

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#83]
Specially if I'm done with what I'm working on #80, this project will be more like an F# project, than a general .NET one.

After all, computation expressions like `gen` and `property` (and what I'll probably come up with #80) aren't consumable outside of F#.

I think that should be a fair rename, like we have haskell-hedgehog (instead of ghc-hedgehog) and scala-hedgehog (instead of jvm-hedgehog).

**Comment by jystic** [comment]
I had hoped that we could have a subset of this library which would be usable from C#, but I could be convinced otherwise.

I don't think that it would ever be possible for the scala-hedgehog to be used from Java on the other hand, as the features we're using of Scala's type system are far away from what Java supports.

**Comment by moodmosaic** [comment]
>I had hoped that we could have a subset of this library which would be usable from C#

This would require a bit of extra maintenance from our side, and I can't convince myself that it's worth it...

Basically, we'd have to create and maintain some sort of [façade](https://en.wikipedia.org/wiki/Facade_pattern), to make it easier for C# developers to call in to our various F# functions in the `Gen` and `Property` modules.

I'm not saying that it's not possible to use Hedgehog from C# as-is, just that it can easily cause a headache:

```c#
using Hedgehog;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;
using System;
using System.Linq;

class Program
{
    static void Main()
    {
        var g =
            Gen.list(Gen.@int);
        var k =
            FSharpFunc<FSharpList<int>, Property<Unit>>.FromConverter(
                new Converter<FSharpList<int>, Property<Unit>>(xs =>
                    PropertyModule.ofBool(
                        Enumerable.Reverse(Enumerable.Reverse(xs)).SequenceEqual(
                            xs))));
        var p =
            PropertyModule.forAll(
                g, k);

        PropertyModule.print(p);
        // +++ OK, passed 100 tests.
    }
}
```

The above program, can be written 'natively' as:

```fsharp
module Proram

open Hedgehog

let g =
    Gen.list Gen.int
let p =
    fun xs ->
        List.rev (List.rev xs) = xs
        |> Property.ofBool
    |> Property.forAll g
Property.print p
// +++ OK, passed 100 tests.
```

Of course, the idiomatic way of using Hedgehog is:

```f#
module Proram

open Hedgehog

let g =
    Gen.list Gen.int
let p =
    property {
        let! xs = g
        return List.rev (List.rev xs) = xs
    }
Property.print p
```

Two of the most important strengths of Hedgehog is that you get
 1. shrinking for free
 2. an easy way of writing properties with the `property` expression

By promoting that a subset of the codebase is usable in C#, and VB.NET, we're basically throwing away `2.`, and I'd prefer not to do that.

---

Instead, if someone wants to write property-based tests for a C# codebase, he or she could write these tests in F#. After all, it's perfectly fine to have both C# and F# projects under the same solution (.sln) file.

**Comment by moodmosaic** [comment]
>as the features we're using of Scala's type system are far away from what Java supports

Yep, it's more or less the same here as well. Units of Measure, Computation Expression, and Type Providers (if I come up with something cool in #80) aren't available in C#.

**Comment by jystic** [comment]
> This would require a bit of extra maintenance from our side, and I can't convince myself that it's worth it...
> Basically, we'd have to create and maintain some sort of façade, to make it easier for C# developers to call in to our various F# functions in the Gen and Property modules.

Yeah I had planned such a wrapper which would allow use via C# lambdas, LINQ, etc. Maybe you're right though, I certainly don't have any plans to work on something like that in short term.

> 2. an easy way of writing properties with the `property` expression

I don't see why something similar can't be achieved separately with LINQ? It won't be as expressive as the computation expressions, but that's the price paid for using a less powerful language.

Fwiw I was thinking something like this:
```csharp
public Property<Unit> PropReverse() =>
    from xs in Gen.List(Gen.Int())
    select Enumerable.Reverse(Enumerable.Reverse(xs)).SequenceEqual(xs)
```

**Comment by moodmosaic** [comment]
>Fwiw I was thinking something like this:
>
>```c#
>public Property<Unit> PropReverse() =>
>    from xs in Gen.List(Gen.Int())
>    select Enumerable.Reverse(Enumerable.Reverse(xs)).SequenceEqual(xs)
>```

This needs some work too,  in order to compile. Right now, it doesn't compile:

```
Error	CS1936	Could not find an implementation of the query pattern for source type 'Gen<FSharpList<int>>'.  'Select' not found.
```

If we get this to compile, then we should probably do this as well:

>Yeah I had planned such a wrapper which would allow use via C# lambdas, LINQ, etc.

---

Still, I find *fsharp-hedgehog* more consistent to the other repository names. Probably it's just me 😃 

![capture1](https://cloud.githubusercontent.com/assets/287532/24825494/05bdd3aa-1c28-11e7-8a51-de1cd9e56c47.PNG)

**Comment by jystic** [comment]
> This needs some work too, in order to compile. Right now, it doesn't compile:

Oh sorry, it was just an example of what I'd expect the API to look like, it won't compile until a C# wrapper is implemented.

**Comment by jystic** [comment]
Ultimately I'm happy to do the rename if you feel strongly about it, I'm not sure that I'll get to a C# wrapper for this any time soon.

**Comment by moodmosaic** [comment]
>Ultimately I'm happy to do the rename if you feel strongly about it, I'm not sure that I'll get to a C# wrapper for this any time soon.

Yeah, and we may easily do a C# wrapper once we reach version `1`.

**Comment by jystic** [comment]
Done 😄

**Comment by moodmosaic** [comment]
That was fast 🎉 😄 👍

**Comment by jystic** [comment]
Actually, I'll leave this open until we fix up any references to the old location (travis / etc)

**Comment by moodmosaic** [comment]
Yes, I'll open a pull request during the weekend.

**Comment by moodmosaic** [comment]
I'll also update https://github.com/hedgehogqa/fsharp-hedgehog/pull/81/files as well.
