### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by Porges** [hedgehogqa/fsharp-hedgehog#88]
Quick question first: would you accept a PR for C# support in the F# repository, or prefer that it's a separate package?

Otherwise, these are the things (that I know of...) that are needed for nice C# integration:
- [x] Potentially: depend on the FSharp.Core nuget package so that Hedgehog works without additional setup when installed into a C# project.
- [ ] Use `CompiledNameAttribute` to make the real names of the functions more usable from C# (e.g. the byte combinator is currently `Gen.@byte`!) This will be a binary-breaking change.
- [ ] Add extension methods for `Select{Many,}` etc, to allow use of query syntax with `Gen`.
- [ ] Figure out exactly how to expose `Property` to C# code. Assertions won't work in query syntax, so might need to work on something with a boolean return value.

**Comment by jystic** [comment]
There was a bit of discussion here related to that: https://github.com/hedgehogqa/fsharp-hedgehog/issues/83

It is something I'd like to see eventually

**Comment by moodmosaic** [comment]
We've had a similar discussion with @jystic in #83 (see [this](https://github.com/hedgehogqa/fsharp-hedgehog/issues/83#issuecomment-292650360) comment, for example). In short, this is a good idea, but we've had no plans to have such a [façade](https://en.wikipedia.org/wiki/Facade_pattern) anytime soon.

**Comment by moodmosaic** [comment]
Yep, so go for it 😃 

>Use `CompiledNameAttribute` to make the real names of the functions more usable from C# (e.g. the byte combinator is currently `Gen.@byte`!) This will be a binary-breaking change.

A breaking change is fine for now. This project follows [SemVer 2.0.0](http://semver.org/spec/v2.0.0.html), and so according to that, until version 1.0.0 is released, major version zero (0.y.z) is for initial development. Anything may change at any time.

**Comment by moodmosaic** [comment]
@Porges, you might want to split this in 2 pull requests, so it gets reviewed faster:

1. A pull request that adds the `CompiledNameAttribute` attribute on the `Gen` and `Property` combinators
2. A pull request that adds support for the LINQ syntax (including the [FSharp.Core 4.0.0.1](https://www.nuget.org/packages/FSharp.Core/4.0.0.1) NuGet Package)

(That's only a suggestion though 😃)

**Comment by Porges** [comment]
FSharp.Core package is addressed by #90 since I had to add it to get the tests running in VS.

**Comment by Porges** [comment]
As far as naming goes, I started off by writing a test to check that all exported functions have PascalCasing compiled-names for use from C#, then going through and adding names where this fails.

Does that make sense? Or would you rather try to identify a subset of the API that should be usable from C#? I figured that if it's public it should be consistent... it's just a little bit noisier to have `[<CompiledName>]` on everything public.

**Comment by moodmosaic** [comment]
>it's just a little bit noisier to have `[<CompiledName>]` on everything public

There's no other way though... 😕

**Comment by moodmosaic** [comment]
In terms of naming, the public API is (or should be) almost the same as [the one in Haskell](https://hackage.haskell.org/package/hedgehog). So, basically, it's two modules `Gen` and `Range` and from these modules, everything that's not internal. /cc @jystic

**Comment by jystic** [comment]
Sounds good to me, I don't mind the `[<CompiledName>]` attribute, that's just how it has to be

I guess the alternative is a wrapper class for gen and range, but probably not necessary

**Comment by moodmosaic** [comment]
Closing this one now that https://github.com/hedgehogqa/fsharp-hedgehog/pull/113 is merged 🎉
