### ISSUE TITLE
Keep Gen module in line with the Haskell version

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#89]
It'd be nice to keep `Gen` (and `Range` after we're done with <del>#85</del>) in sync with [Gen.hs](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/hedgehog/src/Hedgehog/Gen.hs) and [Range.hs](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/hedgehog/src/Hedgehog/Range.hs).

Related to https://github.com/hedgehogqa/fsharp-hedgehog/issues/110.

**Comment by jystic** [comment]
I'm 💯 for this, would be great if people could pick up the library in any of the languages and have it be more or less the same at its core

**Comment by moodmosaic** [comment]
Now that #91 is merged and we have the Range combinators in place, I've started modifying the Gen stuff. I think, now with the Range combinators, the stuff in `Random.fs` might not be needed, but I might be wrong.

**Comment by jystic** [comment]
The main reason for the distinction originally was so that I could implement `Gen.list` with better than default shrinking. But I've figured out how to do that now staying within `Gen` by adding the [Gen.freeze](http://hackage.haskell.org/package/hedgehog-0.1/docs/Hedgehog-Gen.html#v:freeze) combinator, which is also used to get subterm shrinking, something we don't have in F# yet.

So yes, I suspect eventually we can get rid of `Random.fs`

**Comment by moodmosaic** [comment]
>eventually

Hmm...

Okay, then this means, for now, we should probably keep `Random.fs` and just modify it so that it takes a `Range<'a>` where possible. (Just like what needs to be done in `Gen.fs` as well.)

**Comment by jystic** [comment]
Yeah I guess the fact that all the size stuff happens in `Random.fs` is problematic, it probably is a bit of a rejig to get rid of `Random.fs` entirely and bring things in line with the Haskell implementation.

**Comment by jystic** [comment]
Although, we still have `Gen.sized`, so maybe you can use that to get the size in `Gen.fs` and just call `Random.range` (and delete `Random.sizedRange`)

**Comment by moodmosaic** [comment]
Hmm... Yeah, maybe that'll work with `Gen.sized` (I'll have to try it).

And once we have the stuff in `Gen.fs` ready to use the Range combinators we may more easily decide whether/how we should get rid of `Random.fs`.

**Comment by jystic** [comment]
Yeah I think bringing it in line with the Haskell version will mean changing `Gen` to be something like:
```fs
type Gen<'a> =
    | Gen of (Size -> Seed -> Option<Tree<'a>>)
```
or
```fs
type Gen<'a> =
    | Gen of (Size -> Seed -> Tree<Option<'a>>>)
```

Currently we don't allow discards inside generators in F#, which is what the `Option` brings to the table. It's been useful though, so I think it's worth adding at some point.

**Comment by moodmosaic** [comment]
AFAICT, currently both [Shink.hs](https://raw.githubusercontent.com/hedgehogqa/haskell-hedgehog/51ebefc972235d07f25a462b6edbfe3ce507ccbc/hedgehog/src/Hedgehog/Internal/Shrink.hs) and [Shrink.fs](https://raw.githubusercontent.com/hedgehogqa/fsharp-hedgehog/c451bba0c0e8254cd52b69bfce01a61e8c75f2de/src/Hedgehog/Shrink.fs) are similar, so I think it's better if start bringing `Gen.fs` in line with the Haskell version. (Also this means we could get rid of `Random.fs` soon.)

**Comment by moodmosaic** [comment]
What I mean is getting rid of `Random.fs` and make `Gen.fs` similar to the Haskell version. Of course, to keep pull requests focused and small, support for discards inside generators, subterm shrinking, etc, will come later on 😃

**Comment by moodmosaic** [comment]
After a lot of back-and-forth between keeping `Random.fs` versus getting rid of it, I ended up breaking this in small steps

1. #92 is the first step on bringing `Gen.fs` in line with the Haskell version
2. change `Gen` to be something like
    ```f#
    type Gen<'a> =
        | Gen of (Size -> Seed -> Tree<Option<'a>>>)
    ```
3. get rid of `Random`—implement `Gen.list` by adding `Gen.freeze`

**Comment by moodmosaic** [comment]
This should be done as part of #110.
