### ISSUE TITLE
validate.sh

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog#98]
Do we still need [validate.sh](https://github.com/hedgehogqa/fsharp-hedgehog/blob/e22a8355a956bda49836d16220b0ef7848eb8c26/validate.sh)?

**Comment by jystic** [comment]
Yeah? It runs every build and has caught problems on a few occasions so I don't see why we shouldn't keep it

**Comment by moodmosaic** [comment]
Oh, yes, fair enough 👍 I couldn't remember the exact reason, but yes I think it can find out also if there are mixed line-endings, etc.
